<a href="https://colab.research.google.com/github/lricci03/challengedata/blob/main/CFM2024-new/cfm2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CFM 2024 Datachallenge

Models:
* Simple RNN, 1-layer GRU, 1-layer LSTM, simplified WaveNet
* 2-layers GRU (Deep GRU Model): trained for 60 epochs, validation accuracy 61%.

In [ ]:
import torch
import torch.nn as nn

if torch.cuda.is_available():
  device = 'cuda'
elif torch.backends.mps.is_available():
  device = 'mps'
else:
  device = 'cpu'

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

# drive.flush_and_unmount()
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [ ]:
from pathlib import Path

DATA_DIR = Path(
    "/content/drive/MyDrive/Challengedata"
)

print(DATA_DIR.exists())

True

The original csv file is 1.2GB. Locally in CSV we convert it into a parquet file

```
import duckdb

# convert X_train_N1UvY30.csv into Xtrain.parquet
duckdb.sql("""
COPY (
    SELECT *
    FROM read_csv_auto('../X_train_N1UvY30.csv')
)
TO 'Xtrain.parquet'
(FORMAT PARQUET, COMPRESSION ZSTD);
""")
```

## Preprocessing

Upload the data in a dataframe and look at the first 5 rows.

In [ ]:
from pathlib import Path

path = Path("/content/drive/MyDrive/Challengedata/Xtrain.parquet")

df_features = pd.read_parquet(path)

df_features.head()

,obs_id,venue,order_id,action,side,price,bid,ask,bid_size,ask_size,trade,flux
0,0,4,0,A,A,0.30,0.0,0.01,100,1,False,100
1,0,4,1,A,B,-0.17,0.0,0.01,100,1,False,100
2,0,4,2,D,A,0.28,0.0,0.01,100,1,False,-100
3,0,4,3,A,A,0.30,0.0,0.01,100,1,False,100
4,0,4,4,D,A,0.37,0.0,0.01,100,1,False,-100

In [ ]:
df_features.shape

(16080000, 12)

In [ ]:
df_features.columns

Index(['obs_id', 'venue', 'order_id', 'action', 'side', 'price', 'bid', 'ask',
       'bid_size', 'ask_size', 'trade', 'flux'],
      dtype='object')

Upload the targets

In [ ]:
df_targets = pd.read_csv("/content/drive/MyDrive/Challengedata/y_train_or6m3Ta.csv")

df_targets.head()

   obs_id  eqt_code_cat
0       0            10
1       1            15
2       2             0
3       3            13
4       4             0

`order_id` are too many for one-hot encoding and most importantly it is preserved across observations.

We extract two informations out of it:
- order_seen_before
- order_previous_count

Since we want to create these features as well for the test set later on, we define a function that does it.

In [ ]:
def add_order_features(df):

    # how many previous events involved this same order
    df["order_previous_count"] = (
        df.groupby(["obs_id", "order_id"])
          .cumcount()
          .astype("float32")
    )

    # whether this order was seen before
    df["order_seen_before"] = (
        df["order_previous_count"] > 0
    ).astype("float32")

    # raw ID no longer needed
    df.drop("order_id", axis=1, inplace=True)

    return df

In [ ]:
df_features = add_order_features(df_features)

One-hot-encoding

In [ ]:
df_features = df_features[[
    "obs_id",
    "price", "bid", "ask",
    "bid_size", "ask_size",
    "flux",
    "action", "venue", "side", "trade",
    "order_previous_count",
    "order_seen_before"
]]

In [ ]:
num_attribs = ['price', 'bid', 'ask', 'bid_size', 'ask_size', 'flux', 'trade', 'order_seen_before', 'order_previous_count']
cat_attribs = ['venue', 'action', 'side']

In [ ]:
df_features[num_attribs] = df_features[num_attribs].astype("float32")

In [ ]:
df_features = pd.get_dummies(df_features, columns=cat_attribs, dtype="float32")

## Train and Validation Split

In [ ]:
df_features = df_features.set_index("obs_id")
df_targets = df_targets.set_index("obs_id")

In [ ]:
from sklearn.model_selection import train_test_split

train_ids, val_ids = train_test_split(
    df_targets.index,
    test_size=0.2,
    random_state=42
)

In [ ]:
X_train = df_features.loc[train_ids]
X_val   = df_features.loc[val_ids]

y_train = df_targets.loc[train_ids]
y_val   = df_targets.loc[val_ids]

In [ ]:
print(df_features.isna().sum())

price                   0
bid                     0
ask                     0
bid_size                0
ask_size                0
flux                    0
trade                   0
order_previous_count    0
order_seen_before       0
venue_0                 0
venue_1                 0
venue_2                 0
venue_3                 0
venue_4                 0
venue_5                 0
action_A                0
action_D                0
action_U                0
side_A                  0
side_B                  0
dtype: int64

## Convert to tensors

Number of features

In [ ]:
n_features = X_train.shape[1]

print(n_features)

20

In [ ]:
# Reshape X. This reinterprets every consecutive block of 100 rows as one sample.
# The *-1* means: infer this dimension automatically

X_train = torch.tensor(
    X_train.to_numpy(),
    dtype=torch.float32
).reshape(-1, 100, n_features)

X_val = torch.tensor(
    X_val.to_numpy(),
    dtype=torch.float32
).reshape(-1, 100, n_features)

# For classification, the targets should be integers, not floats -> `dtype=torch.long`

y_train = torch.tensor(
    y_train["eqt_code_cat"].to_numpy(),
    dtype=torch.long
)

y_val = torch.tensor(
    y_val["eqt_code_cat"].to_numpy(),
    dtype=torch.long
)

In [ ]:
print(torch.isnan(X_train).any())
print(torch.isnan(X_val).any())

tensor(False)
tensor(False)

Delete the dataframes

In [ ]:
import gc

del df_features, df_targets
gc.collect()

0

In [ ]:
print("train_set shape:", X_train.shape)
print("y_train shape:", y_train.shape)

train_set shape: torch.Size([128640, 100, 20])
y_train shape: torch.Size([128640])

## Dataset and Dataloader

This is not needed if we already reshaped X. We can just use TensorDataset.

In [ ]:
class StockDataset(torch.utils.data.Dataset):
  def __init__(self, features, targets):
    self.features = features
    self.targets = targets

  def __len__(self):
    return len(self.targets) # number of samples

  def __getitem__(self, idx):
    window = self.features[100* idx: 100*(idx + 1)]
    target = self.targets[idx]
    return window, target

In [ ]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [ ]:
valid_dataset = TensorDataset(X_val, y_val)
valid_loader = DataLoader(valid_dataset, batch_size=32)

Shape of dataset features and shape of dataset output

In [ ]:
train_dataset[0][0].shape, train_dataset[0][1].shape

(torch.Size([100, 20]), torch.Size([]))

The shape of the target is a scalar, which is correct for `CrossEntropyLoss` when we do a classification problem.

## Train and evaluation functions

In [ ]:
%pip install -q torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 27.4 MB/s eta 0:00:00

In [ ]:
import torchmetrics
import copy

def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)

            y_class = y_pred.argmax(dim=1)
            metric.update(y_class, y_batch)
    return metric.compute()

def train(model, optimizer, loss_fn, metric, train_loader, valid_loader,
          n_epochs, patience=20, factor=0.1):

    best_valid = -float("inf")
    best_model_state = None
    best_epoch = None

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max", # we monitor accuracy
        patience=patience,
        factor=factor)
    history = {"train_losses": [], "train_metrics": [], "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.0
        metric.reset()
        model.train()
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            loss = loss_fn(y_pred, y_batch)

            total_loss += loss.item()
            loss.backward()

            optimizer.step()
            optimizer.zero_grad()

            y_class = y_pred.detach().argmax(dim=1)
            metric.update(y_class, y_batch)

        train_loss = total_loss / len(train_loader)
        train_metric = metric.compute().item()
        val_metric = evaluate_tm(model, valid_loader, metric).item()

        if val_metric > best_valid:
          best_valid = val_metric
          best_model_state = copy.deepcopy(model.state_dict())
          best_epoch = epoch +1 # +1 bc epoch starts at 0

        history["train_losses"].append(train_loss)
        history["train_metrics"].append(train_metric)
        history["valid_metrics"].append(val_metric)

        scheduler.step(val_metric)


        print(f"Epoch {epoch + 1}/{n_epochs}, "
              f"train loss: {history['train_losses'][-1]:.4f}, "
              f"train metric: {history['train_metrics'][-1]:.4f}, "
              f"valid metric: {history['valid_metrics'][-1]:.4f}")

    model.load_state_dict(best_model_state)
    print("Best epoch:", best_epoch)
    print("Best validation accuracy:", best_valid)

    return history

## Comparing different models

### Simple RNN model

In [ ]:
class SimpleRnnModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

input_size = number of features is 15

output_size = number of classes is 24

In [ ]:
torch.manual_seed(42)

simple_model = SimpleRnnModel(input_size=15, hidden_size=32, output_size=24).to(device)

In [ ]:
torch.manual_seed(42)

optimizer = torch.optim.NAdam(simple_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(simple_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 3.1841, train metric: 0.0515, valid metric: 0.0631
Epoch 2/50, train loss: 3.1056, train metric: 0.0674, valid metric: 0.0729
Epoch 3/50, train loss: 3.0011, train metric: 0.0783, valid metric: 0.0849
Epoch 4/50, train loss: 2.9319, train metric: 0.0871, valid metric: 0.0908
Epoch 5/50, train loss: 2.9084, train metric: 0.0915, valid metric: 0.0914
Epoch 6/50, train loss: 2.8959, train metric: 0.0929, valid metric: 0.0938
Epoch 7/50, train loss: 2.8891, train metric: 0.0947, valid metric: 0.0930
Epoch 8/50, train loss: 2.8839, train metric: 0.0949, valid metric: 0.0975
Epoch 9/50, train loss: 2.8796, train metric: 0.0961, valid metric: 0.0961
Epoch 10/50, train loss: 2.8757, train metric: 0.0978, valid metric: 0.0966
Epoch 11/50, train loss: 2.8723, train metric: 0.0980, valid metric: 0.0987
Epoch 12/50, train loss: 2.8683, train metric: 0.0990, valid metric: 0.0999
Epoch 13/50, train loss: 2.8632, train metric: 0.1001, valid metric: 0.1001
Epoch 14/50, train loss: 2.8579, train metric: 0.1024, valid metric: 0.1025
Epoch 15/50, train loss: 2.8512, train metric: 0.1024, valid metric: 0.1051
Epoch 16/50, train loss: 2.8407, train metric: 0.1050, valid metric: 0.1078
Epoch 17/50, train loss: 2.8261, train metric: 0.1062, valid metric: 0.1043
Epoch 18/50, train loss: 2.8313, train metric: 0.1046, valid metric: 0.1061
Epoch 19/50, train loss: 2.8177, train metric: 0.1076, valid metric: 0.1098
Epoch 20/50, train loss: 2.8189, train metric: 0.1077, valid metric: 0.1099
Epoch 21/50, train loss: 2.8118, train metric: 0.1075, valid metric: 0.1116
Epoch 22/50, train loss: 2.8241, train metric: 0.1063, valid metric: 0.1042
Epoch 23/50, train loss: 2.8158, train metric: 0.1080, valid metric: 0.1098
Epoch 24/50, train loss: 2.8117, train metric: 0.1083, valid metric: 0.1029
Epoch 25/50, train loss: 2.8094, train metric: 0.1085, valid metric: 0.1093
Epoch 26/50, train loss: 2.8354, train metric: 0.1060, valid metric: 0.1088
Epoch 27/50, train loss: 2.8360, train metric: 0.1052, valid metric: 0.1053
Epoch 28/50, train loss: 2.8428, train metric: 0.1055, valid metric: 0.1069
Epoch 29/50, train loss: 2.8510, train metric: 0.1033, valid metric: 0.1076
Epoch 30/50, train loss: 2.8401, train metric: 0.1039, valid metric: 0.1049
Epoch 31/50, train loss: 2.8131, train metric: 0.1082, valid metric: 0.1123
Epoch 32/50, train loss: 2.8439, train metric: 0.1042, valid metric: 0.1022
Epoch 33/50, train loss: 2.8296, train metric: 0.1094, valid metric: 0.1078
Epoch 34/50, train loss: 2.8617, train metric: 0.1029, valid metric: 0.1069
Epoch 35/50, train loss: 2.8606, train metric: 0.1044, valid metric: 0.0989
Epoch 36/50, train loss: 2.8491, train metric: 0.1068, valid metric: 0.1078
Epoch 37/50, train loss: 2.8069, train metric: 0.1077, valid metric: 0.1107
Epoch 38/50, train loss: 2.8174, train metric: 0.1076, valid metric: 0.1112
Epoch 39/50, train loss: 2.8337, train metric: 0.1069, valid metric: 0.1143
Epoch 40/50, train loss: 2.7655, train metric: 0.1148, valid metric: 0.1164
Epoch 41/50, train loss: 2.8038, train metric: 0.1111, valid metric: 0.1162
Epoch 42/50, train loss: 2.8410, train metric: 0.1067, valid metric: 0.1010
Epoch 43/50, train loss: 2.8270, train metric: 0.1102, valid metric: 0.1167
Epoch 44/50, train loss: 2.7740, train metric: 0.1159, valid metric: 0.1051
Epoch 45/50, train loss: 2.8157, train metric: 0.1108, valid metric: 0.1086
Epoch 46/50, train loss: 2.7985, train metric: 0.1139, valid metric: 0.0988
Epoch 47/50, train loss: 2.8099, train metric: 0.1133, valid metric: 0.1145
Epoch 48/50, train loss: 2.7938, train metric: 0.1140, valid metric: 0.1170
Epoch 49/50, train loss: 2.7623, train metric: 0.1177, valid metric: 0.1257
Epoch 50/50, train loss: 2.7361, train metric: 0.1207, valid metric: 0.1225

Look at some predictions

In [ ]:
for idx in range(10):
    X, y = valid_dataset[idx]
    X = X.to(device)
    y = y.to(device)

    with torch.no_grad():
        logits = simple_model(X.unsqueeze(0)) # add batch dimension: (100,15) -> (1,100,15)
        pred = logits.argmax(dim=1).item()

    print(f"idx={idx}, predicted={pred}, actual={y.item()}")

idx=0, predicted=15, actual=2
idx=1, predicted=18, actual=18
idx=2, predicted=3, actual=8
idx=3, predicted=21, actual=1
idx=4, predicted=21, actual=6
idx=5, predicted=5, actual=18
idx=6, predicted=3, actual=4
idx=7, predicted=5, actual=7
idx=8, predicted=13, actual=13
idx=9, predicted=23, actual=1

### GRU MODEL

In [ ]:
class GRUModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.GRU(input_size, hidden_size, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

gru_model = GRUModel(input_size=15, hidden_size=32, output_size=24).to(device)

In [ ]:
torch.manual_seed(42)

optimizer = torch.optim.NAdam(gru_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

gru_history = train(gru_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 3.0683, train metric: 0.0698, valid metric: 0.0836
Epoch 2/50, train loss: 2.9310, train metric: 0.0889, valid metric: 0.0973
Epoch 3/50, train loss: 2.8508, train metric: 0.1025, valid metric: 0.1126
Epoch 4/50, train loss: 2.7615, train metric: 0.1200, valid metric: 0.1230
Epoch 5/50, train loss: 2.6931, train metric: 0.1296, valid metric: 0.1311
Epoch 6/50, train loss: 2.6494, train metric: 0.1363, valid metric: 0.1410
Epoch 7/50, train loss: 2.6174, train metric: 0.1433, valid metric: 0.1466
Epoch 8/50, train loss: 2.5890, train metric: 0.1495, valid metric: 0.1499
Epoch 9/50, train loss: 2.5642, train metric: 0.1549, valid metric: 0.1578
Epoch 10/50, train loss: 2.5421, train metric: 0.1590, valid metric: 0.1639
Epoch 11/50, train loss: 2.5212, train metric: 0.1653, valid metric: 0.1660
Epoch 12/50, train loss: 2.5022, train metric: 0.1696, valid metric: 0.1709
Epoch 13/50, train loss: 2.4842, train metric: 0.1759, valid metric: 0.1774
Epoch 14/50, train loss: 2.4650, train metric: 0.1814, valid metric: 0.1864
Epoch 15/50, train loss: 2.4441, train metric: 0.1872, valid metric: 0.1899
Epoch 16/50, train loss: 2.4275, train metric: 0.1939, valid metric: 0.1934
Epoch 17/50, train loss: 2.4130, train metric: 0.1973, valid metric: 0.1984
Epoch 18/50, train loss: 2.4000, train metric: 0.2009, valid metric: 0.2043
Epoch 19/50, train loss: 2.3877, train metric: 0.2051, valid metric: 0.2076
Epoch 20/50, train loss: 2.3754, train metric: 0.2105, valid metric: 0.2054
Epoch 21/50, train loss: 2.3629, train metric: 0.2134, valid metric: 0.2150
Epoch 22/50, train loss: 2.3496, train metric: 0.2178, valid metric: 0.2165
Epoch 23/50, train loss: 2.3375, train metric: 0.2228, valid metric: 0.2193
Epoch 24/50, train loss: 2.3243, train metric: 0.2265, valid metric: 0.2277
Epoch 25/50, train loss: 2.3119, train metric: 0.2323, valid metric: 0.2334
Epoch 26/50, train loss: 2.2985, train metric: 0.2372, valid metric: 0.2313
Epoch 27/50, train loss: 2.2839, train metric: 0.2404, valid metric: 0.2446
Epoch 28/50, train loss: 2.2709, train metric: 0.2449, valid metric: 0.2523
Epoch 29/50, train loss: 2.2581, train metric: 0.2495, valid metric: 0.2483
Epoch 30/50, train loss: 2.2437, train metric: 0.2560, valid metric: 0.2587
Epoch 31/50, train loss: 2.2270, train metric: 0.2616, valid metric: 0.2664
Epoch 32/50, train loss: 2.2144, train metric: 0.2652, valid metric: 0.2633
Epoch 33/50, train loss: 2.2019, train metric: 0.2705, valid metric: 0.2752
Epoch 34/50, train loss: 2.1899, train metric: 0.2739, valid metric: 0.2746
Epoch 35/50, train loss: 2.1792, train metric: 0.2771, valid metric: 0.2794
Epoch 36/50, train loss: 2.1703, train metric: 0.2793, valid metric: 0.2796
Epoch 37/50, train loss: 2.1612, train metric: 0.2818, valid metric: 0.2807
Epoch 38/50, train loss: 2.1570, train metric: 0.2822, valid metric: 0.2864
Epoch 39/50, train loss: 2.1455, train metric: 0.2868, valid metric: 0.2825
Epoch 40/50, train loss: 2.1377, train metric: 0.2898, valid metric: 0.2859
Epoch 41/50, train loss: 2.1321, train metric: 0.2898, valid metric: 0.2942
Epoch 42/50, train loss: 2.1242, train metric: 0.2926, valid metric: 0.2951
Epoch 43/50, train loss: 2.1181, train metric: 0.2954, valid metric: 0.2969
Epoch 44/50, train loss: 2.1135, train metric: 0.2975, valid metric: 0.2942
Epoch 45/50, train loss: 2.1070, train metric: 0.2996, valid metric: 0.2990
Epoch 46/50, train loss: 2.1012, train metric: 0.3006, valid metric: 0.2961
Epoch 47/50, train loss: 2.0978, train metric: 0.3024, valid metric: 0.2980
Epoch 48/50, train loss: 2.0926, train metric: 0.3043, valid metric: 0.2983
Epoch 49/50, train loss: 2.0877, train metric: 0.3036, valid metric: 0.3072
Epoch 50/50, train loss: 2.0818, train metric: 0.3069, valid metric: 0.3065

In [ ]:
for idx in range(10):
    X, y = valid_dataset[idx]
    X = X.to(device)
    y = y.to(device)

    with torch.no_grad():
        gru_logits = gru_model(X.unsqueeze(0)) # add batch dimension: (100,15) -> (1,100,15)
        rnn_logits = simple_model(X.unsqueeze(0))
        gru_pred = gru_logits.argmax(dim=1).item()
        rnn_pred = rnn_logits.argmax(dim=1).item()

    print(f"idx={idx}, gru predicted={gru_pred}, rnn predicted={rnn_pred} actual={y.item()}")

idx=0, gru predicted=2, rnn predicted=15 actual=2
idx=1, gru predicted=10, rnn predicted=18 actual=18
idx=2, gru predicted=8, rnn predicted=3 actual=8
idx=3, gru predicted=1, rnn predicted=21 actual=1
idx=4, gru predicted=19, rnn predicted=21 actual=6
idx=5, gru predicted=4, rnn predicted=5 actual=18
idx=6, gru predicted=15, rnn predicted=3 actual=4
idx=7, gru predicted=2, rnn predicted=5 actual=7
idx=8, gru predicted=13, rnn predicted=13 actual=13
idx=9, gru predicted=23, rnn predicted=23 actual=1

### LSTM Model

In [ ]:
class LSTMModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.LSTM(input_size, hidden_size, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

lstm_model = LSTMModel(input_size=15, hidden_size=32, output_size=24).to(device)

In [ ]:
torch.manual_seed(42)

optimizer = torch.optim.NAdam(lstm_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

lstm_history = train(lstm_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 3.1331, train metric: 0.0585, valid metric: 0.0751
Epoch 2/50, train loss: 2.9703, train metric: 0.0834, valid metric: 0.0909
Epoch 3/50, train loss: 2.8728, train metric: 0.0986, valid metric: 0.1065
Epoch 4/50, train loss: 2.8163, train metric: 0.1075, valid metric: 0.1102
Epoch 5/50, train loss: 2.8597, train metric: 0.1016, valid metric: 0.1123
Epoch 6/50, train loss: 2.7734, train metric: 0.1128, valid metric: 0.1191
Epoch 7/50, train loss: 2.7494, train metric: 0.1167, valid metric: 0.1212
Epoch 8/50, train loss: 2.7268, train metric: 0.1213, valid metric: 0.1176
Epoch 9/50, train loss: 2.7026, train metric: 0.1260, valid metric: 0.1244
Epoch 10/50, train loss: 2.6832, train metric: 0.1279, valid metric: 0.1268
Epoch 11/50, train loss: 2.6666, train metric: 0.1309, valid metric: 0.1293
Epoch 12/50, train loss: 2.6529, train metric: 0.1328, valid metric: 0.1288
Epoch 13/50, train loss: 2.6360, train metric: 0.1372, valid metric: 0.1333
Epoch 14/50, train loss: 2.6206, train metric: 0.1387, valid metric: 0.1383
Epoch 15/50, train loss: 2.6096, train metric: 0.1413, valid metric: 0.1394
Epoch 16/50, train loss: 2.5981, train metric: 0.1440, valid metric: 0.1430
Epoch 17/50, train loss: 2.5860, train metric: 0.1478, valid metric: 0.1455
Epoch 18/50, train loss: 2.5756, train metric: 0.1504, valid metric: 0.1460
Epoch 19/50, train loss: 2.5650, train metric: 0.1519, valid metric: 0.1480
Epoch 20/50, train loss: 2.5584, train metric: 0.1540, valid metric: 0.1532
Epoch 21/50, train loss: 2.5502, train metric: 0.1567, valid metric: 0.1539
Epoch 22/50, train loss: 2.5405, train metric: 0.1583, valid metric: 0.1556
Epoch 23/50, train loss: 2.5306, train metric: 0.1593, valid metric: 0.1593
Epoch 24/50, train loss: 2.5220, train metric: 0.1634, valid metric: 0.1602
Epoch 25/50, train loss: 2.5151, train metric: 0.1633, valid metric: 0.1599
Epoch 26/50, train loss: 2.5057, train metric: 0.1658, valid metric: 0.1654
Epoch 27/50, train loss: 2.4959, train metric: 0.1686, valid metric: 0.1681
Epoch 28/50, train loss: 2.4875, train metric: 0.1700, valid metric: 0.1710
Epoch 29/50, train loss: 2.4785, train metric: 0.1728, valid metric: 0.1727
Epoch 30/50, train loss: 2.4717, train metric: 0.1743, valid metric: 0.1725
Epoch 31/50, train loss: 2.4621, train metric: 0.1785, valid metric: 0.1725
Epoch 32/50, train loss: 2.4552, train metric: 0.1821, valid metric: 0.1808
Epoch 33/50, train loss: 2.4423, train metric: 0.1844, valid metric: 0.1810
Epoch 34/50, train loss: 2.4333, train metric: 0.1884, valid metric: 0.1860
Epoch 35/50, train loss: 2.4229, train metric: 0.1914, valid metric: 0.1911
Epoch 36/50, train loss: 2.4135, train metric: 0.1947, valid metric: 0.1928
Epoch 37/50, train loss: 2.4046, train metric: 0.1974, valid metric: 0.1998
Epoch 38/50, train loss: 2.3950, train metric: 0.2010, valid metric: 0.2017
Epoch 39/50, train loss: 2.3854, train metric: 0.2054, valid metric: 0.2021
Epoch 40/50, train loss: 2.3824, train metric: 0.2080, valid metric: 0.2014
Epoch 41/50, train loss: 2.3655, train metric: 0.2119, valid metric: 0.2127
Epoch 42/50, train loss: 2.3561, train metric: 0.2160, valid metric: 0.2137
Epoch 43/50, train loss: 2.3424, train metric: 0.2202, valid metric: 0.2179
Epoch 44/50, train loss: 2.3328, train metric: 0.2236, valid metric: 0.2258
Epoch 45/50, train loss: 2.3205, train metric: 0.2286, valid metric: 0.2208
Epoch 46/50, train loss: 2.3118, train metric: 0.2298, valid metric: 0.2277
Epoch 47/50, train loss: 2.3028, train metric: 0.2340, valid metric: 0.2293
Epoch 48/50, train loss: 2.2916, train metric: 0.2354, valid metric: 0.2283
Epoch 49/50, train loss: 2.2896, train metric: 0.2365, valid metric: 0.2329
Epoch 50/50, train loss: 2.2789, train metric: 0.2395, valid metric: 0.2399

### CNN - simplified WaveNet
*WaveNet*: stacking 1D convolutional layers, doubling the dilation rate (how spread apart each neuron's inputs are) at every layer. The first conv layer sees two time steps at a time, the nex one sees four time steps, etc.

The lower layers learn short-term patterns, while the higher layers learn long-term patterns.

Custom CausalConv1d module that acts just like an nn.Conv1d module, except the inuts get padded on the left side by the appropriate amount to ensure the sequence preserves the same length.

- kernel_size will be 2 for each layer
- dilation will increase: 1,2,4,8 and then again 1,2,4,8

In [ ]:
import torch.nn.functional as F

class CausalConv1d(nn.Conv1d):
  def forward(self, X):
    padding = (self.kernel_size[0] - 1) * self.dilation[0] # calculate the size of the left-padding we need
    X = F.pad(X, (padding, 0))  # X is the tensor to pad, (padding, 0) is how much to pad to the left and right in the time dimension
    return super().forward(X)

WaveNet model.

Must swap the two dimensions of the nn.Conv1d layer's inputs and outputs: nn.Conv1d expects inputs of shape [*batch size, input features, sequence length*] and produces outputs of shape [*batch size, output features, sequence length*]

while we have inputs [*batch size, sequence length, input features*] (with sequence length 100, input features 15).

We don't need the prediction for all 100 time steps, so we then take the last time step: Z[:, :, -1].

In [ ]:
class WavenetModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    layers = []
    for dilation in (1,2,4,8) * 2: # (1,2,4,8,1,2,4,8)
      conv = CausalConv1d(input_size, hidden_size, kernel_size=2, dilation=dilation)
      layers += [conv, nn.ReLU()]
      input_size = hidden_size
    self.convs = nn.Sequential(*layers)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    Z = X.permute(0,2,1)
    Z = self.convs(Z)
    Z = Z[:, :, -1]
    return self.output(Z)

In [ ]:
torch.manual_seed(42)
wavenet_model = WavenetModel(input_size=15, hidden_size=32, output_size=24).to(device)

optimizer = torch.optim.NAdam(wavenet_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

wavenet_history = train(wavenet_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.9142, train metric: 0.0848, valid metric: 0.1032
Epoch 2/50, train loss: 2.7814, train metric: 0.1061, valid metric: 0.1126
Epoch 3/50, train loss: 2.7440, train metric: 0.1164, valid metric: 0.1087
Epoch 4/50, train loss: 2.7223, train metric: 0.1219, valid metric: 0.1248
Epoch 5/50, train loss: 2.7039, train metric: 0.1277, valid metric: 0.1318
Epoch 6/50, train loss: 2.6913, train metric: 0.1303, valid metric: 0.1288
Epoch 7/50, train loss: 2.6810, train metric: 0.1330, valid metric: 0.1341
Epoch 8/50, train loss: 2.6719, train metric: 0.1353, valid metric: 0.1375
Epoch 9/50, train loss: 2.6642, train metric: 0.1371, valid metric: 0.1387
Epoch 10/50, train loss: 2.6568, train metric: 0.1403, valid metric: 0.1314
Epoch 11/50, train loss: 2.6495, train metric: 0.1417, valid metric: 0.1409
Epoch 12/50, train loss: 2.6431, train metric: 0.1436, valid metric: 0.1442
Epoch 13/50, train loss: 2.6340, train metric: 0.1471, valid metric: 0.1421
Epoch 14/50, train loss: 2.6268, train metric: 0.1484, valid metric: 0.1490
Epoch 15/50, train loss: 2.6181, train metric: 0.1524, valid metric: 0.1484
Epoch 16/50, train loss: 2.6098, train metric: 0.1549, valid metric: 0.1517
Epoch 17/50, train loss: 2.6016, train metric: 0.1593, valid metric: 0.1594
Epoch 18/50, train loss: 2.5922, train metric: 0.1625, valid metric: 0.1583
Epoch 19/50, train loss: 2.5848, train metric: 0.1657, valid metric: 0.1595
Epoch 20/50, train loss: 2.5774, train metric: 0.1678, valid metric: 0.1643
Epoch 21/50, train loss: 2.5704, train metric: 0.1703, valid metric: 0.1656
Epoch 22/50, train loss: 2.5633, train metric: 0.1729, valid metric: 0.1710
Epoch 23/50, train loss: 2.5557, train metric: 0.1744, valid metric: 0.1716
Epoch 24/50, train loss: 2.5483, train metric: 0.1772, valid metric: 0.1679
Epoch 25/50, train loss: 2.5414, train metric: 0.1791, valid metric: 0.1678
Epoch 26/50, train loss: 2.5358, train metric: 0.1817, valid metric: 0.1750
Epoch 27/50, train loss: 2.5288, train metric: 0.1834, valid metric: 0.1738
Epoch 28/50, train loss: 2.5232, train metric: 0.1852, valid metric: 0.1797
Epoch 29/50, train loss: 2.5183, train metric: 0.1866, valid metric: 0.1764
Epoch 30/50, train loss: 2.5118, train metric: 0.1878, valid metric: 0.1821
Epoch 31/50, train loss: 2.5075, train metric: 0.1905, valid metric: 0.1811
Epoch 32/50, train loss: 2.5017, train metric: 0.1924, valid metric: 0.1872
Epoch 33/50, train loss: 2.4979, train metric: 0.1936, valid metric: 0.1868
Epoch 34/50, train loss: 2.4922, train metric: 0.1958, valid metric: 0.1864
Epoch 35/50, train loss: 2.4872, train metric: 0.1974, valid metric: 0.1896
Epoch 36/50, train loss: 2.4836, train metric: 0.1978, valid metric: 0.1892
Epoch 37/50, train loss: 2.4778, train metric: 0.2002, valid metric: 0.1871
Epoch 38/50, train loss: 2.4737, train metric: 0.2000, valid metric: 0.1921
Epoch 39/50, train loss: 2.4681, train metric: 0.2016, valid metric: 0.1933
Epoch 40/50, train loss: 2.4645, train metric: 0.2043, valid metric: 0.1961
Epoch 41/50, train loss: 2.4588, train metric: 0.2047, valid metric: 0.1934
Epoch 42/50, train loss: 2.4554, train metric: 0.2052, valid metric: 0.1929
Epoch 43/50, train loss: 2.4492, train metric: 0.2080, valid metric: 0.2013
Epoch 44/50, train loss: 2.4459, train metric: 0.2084, valid metric: 0.1969
Epoch 45/50, train loss: 2.4415, train metric: 0.2106, valid metric: 0.1963
Epoch 46/50, train loss: 2.4362, train metric: 0.2120, valid metric: 0.2001
Epoch 47/50, train loss: 2.4321, train metric: 0.2131, valid metric: 0.1995
Epoch 48/50, train loss: 2.4282, train metric: 0.2132, valid metric: 0.2023
Epoch 49/50, train loss: 2.4223, train metric: 0.2152, valid metric: 0.2023
Epoch 50/50, train loss: 2.4178, train metric: 0.2179, valid metric: 0.1975

## Comparing hidden sizes in GRU Model

Gru Model with hidden size = 64

In [ ]:
torch.manual_seed(42)

gru_model_64 = GRUModel(input_size=15, hidden_size=64, output_size=24).to(device)

optimizer = torch.optim.NAdam(gru_model_64.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

gru_64_history = train(gru_model_64, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 3.0117, train metric: 0.0807, valid metric: 0.1050
Epoch 2/50, train loss: 2.7969, train metric: 0.1153, valid metric: 0.1287
Epoch 3/50, train loss: 2.6821, train metric: 0.1352, valid metric: 0.1394
Epoch 4/50, train loss: 2.6198, train metric: 0.1474, valid metric: 0.1522
Epoch 5/50, train loss: 2.5692, train metric: 0.1583, valid metric: 0.1586
Epoch 6/50, train loss: 2.5222, train metric: 0.1698, valid metric: 0.1699
Epoch 7/50, train loss: 2.4754, train metric: 0.1812, valid metric: 0.1860
Epoch 8/50, train loss: 2.4354, train metric: 0.1936, valid metric: 0.1950
Epoch 9/50, train loss: 2.3985, train metric: 0.2021, valid metric: 0.1990
Epoch 10/50, train loss: 2.3649, train metric: 0.2135, valid metric: 0.2133
Epoch 11/50, train loss: 2.3332, train metric: 0.2212, valid metric: 0.2263
Epoch 12/50, train loss: 2.3029, train metric: 0.2336, valid metric: 0.2262
Epoch 13/50, train loss: 2.2760, train metric: 0.2411, valid metric: 0.2450
Epoch 14/50, train loss: 2.2476, train metric: 0.2503, valid metric: 0.2543
Epoch 15/50, train loss: 2.2162, train metric: 0.2619, valid metric: 0.2632
Epoch 16/50, train loss: 2.1878, train metric: 0.2719, valid metric: 0.2646
Epoch 17/50, train loss: 2.1625, train metric: 0.2793, valid metric: 0.2758
Epoch 18/50, train loss: 2.1390, train metric: 0.2844, valid metric: 0.2800
Epoch 19/50, train loss: 2.1176, train metric: 0.2909, valid metric: 0.2847
Epoch 20/50, train loss: 2.0990, train metric: 0.2969, valid metric: 0.2887
Epoch 21/50, train loss: 2.0799, train metric: 0.3019, valid metric: 0.3021
Epoch 22/50, train loss: 2.0630, train metric: 0.3087, valid metric: 0.3022
Epoch 23/50, train loss: 2.0469, train metric: 0.3140, valid metric: 0.3070
Epoch 24/50, train loss: 2.0329, train metric: 0.3191, valid metric: 0.3021
Epoch 25/50, train loss: 2.0199, train metric: 0.3220, valid metric: 0.3159
Epoch 26/50, train loss: 2.0087, train metric: 0.3262, valid metric: 0.3213
Epoch 27/50, train loss: 1.9942, train metric: 0.3307, valid metric: 0.3303
Epoch 28/50, train loss: 1.9842, train metric: 0.3348, valid metric: 0.3224
Epoch 29/50, train loss: 1.9724, train metric: 0.3378, valid metric: 0.3385
Epoch 30/50, train loss: 1.9638, train metric: 0.3417, valid metric: 0.3372
Epoch 31/50, train loss: 1.9535, train metric: 0.3448, valid metric: 0.3458
Epoch 32/50, train loss: 1.9435, train metric: 0.3470, valid metric: 0.3470
Epoch 33/50, train loss: 1.9334, train metric: 0.3524, valid metric: 0.3407
Epoch 34/50, train loss: 1.9249, train metric: 0.3558, valid metric: 0.3536
Epoch 35/50, train loss: 1.9168, train metric: 0.3582, valid metric: 0.3551
Epoch 36/50, train loss: 1.9089, train metric: 0.3593, valid metric: 0.3382
Epoch 37/50, train loss: 1.8994, train metric: 0.3646, valid metric: 0.3547
Epoch 38/50, train loss: 1.8915, train metric: 0.3675, valid metric: 0.3643
Epoch 39/50, train loss: 1.8829, train metric: 0.3696, valid metric: 0.3647
Epoch 40/50, train loss: 1.8757, train metric: 0.3720, valid metric: 0.3691
Epoch 41/50, train loss: 1.8665, train metric: 0.3757, valid metric: 0.3695
Epoch 42/50, train loss: 1.8576, train metric: 0.3798, valid metric: 0.3745
Epoch 43/50, train loss: 1.8515, train metric: 0.3811, valid metric: 0.3795
Epoch 44/50, train loss: 1.8425, train metric: 0.3852, valid metric: 0.3798
Epoch 45/50, train loss: 1.8356, train metric: 0.3877, valid metric: 0.3782
Epoch 46/50, train loss: 1.8274, train metric: 0.3886, valid metric: 0.3807
Epoch 47/50, train loss: 1.8206, train metric: 0.3911, valid metric: 0.3872
Epoch 48/50, train loss: 1.8138, train metric: 0.3944, valid metric: 0.3911
Epoch 49/50, train loss: 1.8054, train metric: 0.3973, valid metric: 0.3899
Epoch 50/50, train loss: 1.7981, train metric: 0.3990, valid metric: 0.3980

Gru model with hidden size 128

In [ ]:
torch.manual_seed(42)

gru_model_128 = GRUModel(input_size=15, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(gru_model_128.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

gru_128_history = train(gru_model_128, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.9319, train metric: 0.0948, valid metric: 0.1212
Epoch 2/50, train loss: 2.6910, train metric: 0.1376, valid metric: 0.1503
Epoch 3/50, train loss: 2.5801, train metric: 0.1617, valid metric: 0.1625
Epoch 4/50, train loss: 2.5119, train metric: 0.1798, valid metric: 0.1840
Epoch 5/50, train loss: 2.4495, train metric: 0.1967, valid metric: 0.1990
Epoch 6/50, train loss: 2.3915, train metric: 0.2133, valid metric: 0.2131
Epoch 7/50, train loss: 2.3347, train metric: 0.2302, valid metric: 0.2362
Epoch 8/50, train loss: 2.2794, train metric: 0.2499, valid metric: 0.2586
Epoch 9/50, train loss: 2.2235, train metric: 0.2676, valid metric: 0.2685
Epoch 10/50, train loss: 2.1689, train metric: 0.2842, valid metric: 0.2921
Epoch 11/50, train loss: 2.1205, train metric: 0.2995, valid metric: 0.2984
Epoch 12/50, train loss: 2.0797, train metric: 0.3108, valid metric: 0.3157
Epoch 13/50, train loss: 2.0435, train metric: 0.3213, valid metric: 0.3237
Epoch 14/50, train loss: 2.0091, train metric: 0.3327, valid metric: 0.3326
Epoch 15/50, train loss: 1.9792, train metric: 0.3399, valid metric: 0.3299
Epoch 16/50, train loss: 1.9505, train metric: 0.3501, valid metric: 0.3359
Epoch 17/50, train loss: 1.9253, train metric: 0.3585, valid metric: 0.3496
Epoch 18/50, train loss: 1.9002, train metric: 0.3666, valid metric: 0.3661
Epoch 19/50, train loss: 1.8767, train metric: 0.3732, valid metric: 0.3707
Epoch 20/50, train loss: 1.8553, train metric: 0.3806, valid metric: 0.3724
Epoch 21/50, train loss: 1.8339, train metric: 0.3870, valid metric: 0.3812
Epoch 22/50, train loss: 1.8151, train metric: 0.3931, valid metric: 0.3866
Epoch 23/50, train loss: 1.7980, train metric: 0.3989, valid metric: 0.3894
Epoch 24/50, train loss: 1.7804, train metric: 0.4033, valid metric: 0.3982
Epoch 25/50, train loss: 1.7639, train metric: 0.4085, valid metric: 0.3940
Epoch 26/50, train loss: 1.7504, train metric: 0.4147, valid metric: 0.4118
Epoch 27/50, train loss: 1.7368, train metric: 0.4189, valid metric: 0.4078
Epoch 28/50, train loss: 1.7234, train metric: 0.4215, valid metric: 0.4154
Epoch 29/50, train loss: 1.7108, train metric: 0.4264, valid metric: 0.4187
Epoch 30/50, train loss: 1.6982, train metric: 0.4316, valid metric: 0.4080
Epoch 31/50, train loss: 1.6870, train metric: 0.4327, valid metric: 0.4219
Epoch 32/50, train loss: 1.6772, train metric: 0.4369, valid metric: 0.4297
Epoch 33/50, train loss: 1.6660, train metric: 0.4393, valid metric: 0.4301
Epoch 34/50, train loss: 1.6566, train metric: 0.4436, valid metric: 0.4360
Epoch 35/50, train loss: 1.6465, train metric: 0.4467, valid metric: 0.4322
Epoch 36/50, train loss: 1.6376, train metric: 0.4488, valid metric: 0.4381
Epoch 37/50, train loss: 1.6282, train metric: 0.4526, valid metric: 0.4440
Epoch 38/50, train loss: 1.6185, train metric: 0.4558, valid metric: 0.4442
Epoch 39/50, train loss: 1.6101, train metric: 0.4577, valid metric: 0.4504
Epoch 40/50, train loss: 1.6003, train metric: 0.4614, valid metric: 0.4522
Epoch 41/50, train loss: 1.5909, train metric: 0.4660, valid metric: 0.4509
Epoch 42/50, train loss: 1.5821, train metric: 0.4690, valid metric: 0.4505
Epoch 43/50, train loss: 1.5726, train metric: 0.4721, valid metric: 0.4563
Epoch 44/50, train loss: 1.5626, train metric: 0.4747, valid metric: 0.4638
Epoch 45/50, train loss: 1.5556, train metric: 0.4781, valid metric: 0.4608
Epoch 46/50, train loss: 1.5465, train metric: 0.4801, valid metric: 0.4551
Epoch 47/50, train loss: 1.5373, train metric: 0.4833, valid metric: 0.4601
Epoch 48/50, train loss: 1.5292, train metric: 0.4864, valid metric: 0.4760
Epoch 49/50, train loss: 1.5198, train metric: 0.4907, valid metric: 0.4772
Epoch 50/50, train loss: 1.5121, train metric: 0.4923, valid metric: 0.4682

#### Save the model weights

In [ ]:
torch.save(
    gru_model_128.state_dict(),
    "/content/drive/MyDrive/Challengedata/gru_128_model.pt"
)

#### Upload the model weights

In [ ]:
gru_model_128 = GRUModel(
    input_size=15,
    hidden_size=128,
    output_size=24
)

gru_model_128.load_state_dict(
    torch.load("/content/drive/MyDrive/Challengedata/gru_128_model.pt", map_location=device)
)

gru_model_128.to(device)
gru_model_128.eval()

## Create submission

We first need to prepreocess the test data.

We predict the test set using `gru_model_128` and create the submission file.

In [ ]:
test = pd.read_parquet("/content/drive/MyDrive/Challengedata/Xtest.parquet")

In [ ]:
test = test[['obs_id','price', 'bid', 'ask', 'bid_size', 'ask_size', 'flux', 'action', 'venue']]
test['venue'] = test['venue'].apply(str)
test = pd.get_dummies(test, dtype=float)
test = test.set_index('obs_id')

In [ ]:
X_test = torch.tensor(test.values, dtype=torch.float32)
X_test = X_test.reshape(-1, 100, 15)

In [ ]:
del test
gc.collect()

266

Create a test_loader because we want to predict in batches rather than send all the data to the GPU at once.

In [ ]:
test_dataset = TensorDataset(X_test)
test_loader = DataLoader(test_dataset, batch_size=256)

Predict the data

In [ ]:
gru_model_128.eval()

predictions = []

with torch.no_grad():
    for (X_batch,) in test_loader:
        X_batch = X_batch.to(device)

        logits = gru_model_128(X_batch)
        y_pred = logits.argmax(dim=1)

        predictions.extend(y_pred.cpu().numpy())

Save the predictions to csv

In [ ]:
submission = pd.DataFrame({
    "obs_id": range(len(predictions)),
    "eqt_code_cat": predictions
})

submission.to_csv(
    "/content/drive/MyDrive/Challengedata/submission.csv",
    index=False
)

## Deep GRU Model

In [ ]:
class DeepGRUModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.GRU(input_size, hidden_size, num_layers=2, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

deep_gru_model_128 = DeepGRUModel(input_size=20, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(deep_gru_model_128.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(deep_gru_model_128, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.7282, train metric: 0.1251, valid metric: 0.1545
Epoch 2/50, train loss: 2.5432, train metric: 0.1694, valid metric: 0.1809
Epoch 3/50, train loss: 2.4503, train metric: 0.1951, valid metric: 0.1991
Epoch 4/50, train loss: 2.3820, train metric: 0.2115, valid metric: 0.2189
Epoch 5/50, train loss: 2.3161, train metric: 0.2323, valid metric: 0.2440
Epoch 6/50, train loss: 2.2294, train metric: 0.2605, valid metric: 0.2656
Epoch 7/50, train loss: 2.1502, train metric: 0.2816, valid metric: 0.2865
Epoch 8/50, train loss: 2.0827, train metric: 0.3021, valid metric: 0.2975
Epoch 9/50, train loss: 2.0187, train metric: 0.3207, valid metric: 0.3181
Epoch 10/50, train loss: 1.9554, train metric: 0.3428, valid metric: 0.3466
Epoch 11/50, train loss: 1.8979, train metric: 0.3620, valid metric: 0.3584
Epoch 12/50, train loss: 1.8422, train metric: 0.3809, valid metric: 0.3771
Epoch 13/50, train loss: 1.7906, train metric: 0.3989, valid metric: 0.4001
Epoch 14/50, train loss: 1.7388, train metric: 0.4156, valid metric: 0.4137
Epoch 15/50, train loss: 1.6922, train metric: 0.4324, valid metric: 0.4252
Epoch 16/50, train loss: 1.6485, train metric: 0.4448, valid metric: 0.4389
Epoch 17/50, train loss: 1.6111, train metric: 0.4566, valid metric: 0.4556
Epoch 18/50, train loss: 1.5755, train metric: 0.4691, valid metric: 0.4560
Epoch 19/50, train loss: 1.5419, train metric: 0.4800, valid metric: 0.4402
Epoch 20/50, train loss: 1.5103, train metric: 0.4916, valid metric: 0.4752
Epoch 21/50, train loss: 1.4804, train metric: 0.4996, valid metric: 0.4847
Epoch 22/50, train loss: 1.4476, train metric: 0.5122, valid metric: 0.5002
Epoch 23/50, train loss: 1.4224, train metric: 0.5200, valid metric: 0.5104
Epoch 24/50, train loss: 1.3957, train metric: 0.5291, valid metric: 0.5081
Epoch 25/50, train loss: 1.3719, train metric: 0.5363, valid metric: 0.5202
Epoch 26/50, train loss: 1.3485, train metric: 0.5443, valid metric: 0.5210
Epoch 27/50, train loss: 1.3266, train metric: 0.5518, valid metric: 0.5344
Epoch 28/50, train loss: 1.3059, train metric: 0.5583, valid metric: 0.5356
Epoch 29/50, train loss: 1.2869, train metric: 0.5644, valid metric: 0.5270
Epoch 30/50, train loss: 1.2684, train metric: 0.5700, valid metric: 0.5482
Epoch 31/50, train loss: 1.2512, train metric: 0.5764, valid metric: 0.5455
Epoch 32/50, train loss: 1.2334, train metric: 0.5819, valid metric: 0.5536
Epoch 33/50, train loss: 1.2192, train metric: 0.5867, valid metric: 0.5586
Epoch 34/50, train loss: 1.2033, train metric: 0.5920, valid metric: 0.5648
Epoch 35/50, train loss: 1.1894, train metric: 0.5962, valid metric: 0.5677
Epoch 36/50, train loss: 1.1742, train metric: 0.6000, valid metric: 0.5724
Epoch 37/50, train loss: 1.1607, train metric: 0.6061, valid metric: 0.5754
Epoch 38/50, train loss: 1.1467, train metric: 0.6101, valid metric: 0.5672
Epoch 39/50, train loss: 1.1346, train metric: 0.6147, valid metric: 0.5802
Epoch 40/50, train loss: 1.1218, train metric: 0.6178, valid metric: 0.5836
Epoch 41/50, train loss: 1.1105, train metric: 0.6222, valid metric: 0.5830
Epoch 42/50, train loss: 1.0997, train metric: 0.6258, valid metric: 0.5779
Epoch 43/50, train loss: 1.0884, train metric: 0.6297, valid metric: 0.5864
Epoch 44/50, train loss: 1.0755, train metric: 0.6331, valid metric: 0.5913
Epoch 45/50, train loss: 1.0644, train metric: 0.6375, valid metric: 0.5902
Epoch 46/50, train loss: 1.0550, train metric: 0.6391, valid metric: 0.5926
Epoch 47/50, train loss: 1.0446, train metric: 0.6436, valid metric: 0.5966
Epoch 48/50, train loss: 1.0344, train metric: 0.6474, valid metric: 0.5970
Epoch 49/50, train loss: 1.0240, train metric: 0.6492, valid metric: 0.5984
Epoch 50/50, train loss: 1.0164, train metric: 0.6521, valid metric: 0.6035
Best epoch: 50
Best validation accuracy: 0.6034514904022217

In [ ]:
history_2 = train(deep_gru_model_128, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=10)

Epoch 1/10, train loss: 1.0060, train metric: 0.6559, valid metric: 0.5896
Epoch 2/10, train loss: 0.9963, train metric: 0.6588, valid metric: 0.6036
Epoch 3/10, train loss: 0.9874, train metric: 0.6608, valid metric: 0.6084
Epoch 4/10, train loss: 0.9812, train metric: 0.6635, valid metric: 0.6039
Epoch 5/10, train loss: 0.9696, train metric: 0.6663, valid metric: 0.6000
Epoch 6/10, train loss: 0.9614, train metric: 0.6697, valid metric: 0.6113
Epoch 7/10, train loss: 0.9535, train metric: 0.6722, valid metric: 0.6105
Epoch 8/10, train loss: 0.9441, train metric: 0.6746, valid metric: 0.6053
Epoch 9/10, train loss: 0.9372, train metric: 0.6770, valid metric: 0.6135
Epoch 10/10, train loss: 0.9285, train metric: 0.6808, valid metric: 0.6097
Best epoch: 9
Best validation accuracy: 0.6135261058807373

### Save & load model

Save the model: this is trained **without normalization of the inputs** and with 2 gru layers.

In [ ]:
torch.save(
    deep_gru_model_128.state_dict(),
    "/content/drive/MyDrive/Challengedata/deep_gru_model_128.pt"
)

Load the model

In [ ]:
deep_gru_model_128.load_state_dict(
    torch.load("/content/drive/MyDrive/Challengedata/deep_gru_model_128.pt")
)

## Deeper GRU Model

In [ ]:
class DeeperGRUModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.GRU(input_size, hidden_size, num_layers=3, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

deeper_gru_model = DeeperGRUModel(input_size=20, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(deeper_gru_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(deeper_gru_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.7107, train metric: 0.1267, valid metric: 0.1519
Epoch 2/50, train loss: 2.5511, train metric: 0.1644, valid metric: 0.1717
Epoch 3/50, train loss: 2.4563, train metric: 0.1911, valid metric: 0.1931
Epoch 4/50, train loss: 2.3587, train metric: 0.2217, valid metric: 0.2250
Epoch 5/50, train loss: 2.2736, train metric: 0.2493, valid metric: 0.2451

## DownsamplingModel

1D convolutional layer with stride 2 and kernel 4, stacked with two layered GRU

In [ ]:
class DownsamplingModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.conv = nn.Conv1d(input_size, hidden_size, kernel_size=4, stride=2)
    self.gru = nn.GRU(hidden_size, hidden_size, num_layers=2, batch_first=True)
    self.linear = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    Z = X.permute(0,2,1)  # treat ticks as spatial dimension
    Z = self.conv(Z)
    Z = Z.permute(0,2,1) # swap back ticks and feature dimensions
    Z = torch.relu(Z)
    outputs, last_state = self.gru(Z)
    return self.linear(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

downsampling_model = DownsamplingModel(input_size=20, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(downsampling_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(downsampling_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.7482, train metric: 0.1163, valid metric: 0.1342
Epoch 2/50, train loss: 2.5950, train metric: 0.1490, valid metric: 0.1617
Epoch 3/50, train loss: 2.5354, train metric: 0.1701, valid metric: 0.1792
Epoch 4/50, train loss: 2.4760, train metric: 0.1875, valid metric: 0.1800
Epoch 5/50, train loss: 2.4111, train metric: 0.2077, valid metric: 0.2106
Epoch 6/50, train loss: 2.3482, train metric: 0.2284, valid metric: 0.2261
Epoch 7/50, train loss: 2.2875, train metric: 0.2492, valid metric: 0.2535
Epoch 8/50, train loss: 2.2362, train metric: 0.2651, valid metric: 0.2708
Epoch 9/50, train loss: 2.1890, train metric: 0.2797, valid metric: 0.2697
Epoch 10/50, train loss: 2.1495, train metric: 0.2918, valid metric: 0.2911
Epoch 11/50, train loss: 2.1106, train metric: 0.3049, valid metric: 0.2921
Epoch 12/50, train loss: 2.0709, train metric: 0.3160, valid metric: 0.3083
Epoch 13/50, train loss: 2.0403, train metric: 0.3270, valid metric: 0.3201
Epoch 14/50, train loss: 2.0094, train metric: 0.3363, valid metric: 0.3147
Epoch 15/50, train loss: 1.9788, train metric: 0.3457, valid metric: 0.3340
Epoch 16/50, train loss: 1.9500, train metric: 0.3535, valid metric: 0.3430
Epoch 17/50, train loss: 1.9204, train metric: 0.3652, valid metric: 0.3408
Epoch 18/50, train loss: 1.8921, train metric: 0.3721, valid metric: 0.3523
Epoch 19/50, train loss: 1.8630, train metric: 0.3810, valid metric: 0.3611
Epoch 20/50, train loss: 1.8315, train metric: 0.3909, valid metric: 0.3695
Epoch 21/50, train loss: 1.8058, train metric: 0.3989, valid metric: 0.3680
Epoch 22/50, train loss: 1.7783, train metric: 0.4068, valid metric: 0.3797
Epoch 23/50, train loss: 1.7546, train metric: 0.4129, valid metric: 0.3870
Epoch 24/50, train loss: 1.7293, train metric: 0.4215, valid metric: 0.3921
Epoch 25/50, train loss: 1.7059, train metric: 0.4275, valid metric: 0.3971
Epoch 26/50, train loss: 1.6837, train metric: 0.4343, valid metric: 0.4024
Epoch 27/50, train loss: 1.6621, train metric: 0.4409, valid metric: 0.4004
Epoch 28/50, train loss: 1.6412, train metric: 0.4474, valid metric: 0.4050
Epoch 29/50, train loss: 1.6186, train metric: 0.4566, valid metric: 0.4135
Epoch 30/50, train loss: 1.5993, train metric: 0.4598, valid metric: 0.4201
Epoch 31/50, train loss: 1.5831, train metric: 0.4663, valid metric: 0.4239
Epoch 32/50, train loss: 1.5627, train metric: 0.4717, valid metric: 0.4272
Epoch 33/50, train loss: 1.5429, train metric: 0.4793, valid metric: 0.4285
Epoch 34/50, train loss: 1.5262, train metric: 0.4840, valid metric: 0.4321
Epoch 35/50, train loss: 1.5076, train metric: 0.4883, valid metric: 0.4365
Epoch 36/50, train loss: 1.4924, train metric: 0.4954, valid metric: 0.4378
Epoch 37/50, train loss: 1.4749, train metric: 0.4992, valid metric: 0.4416
Epoch 38/50, train loss: 1.4574, train metric: 0.5042, valid metric: 0.4437
Epoch 39/50, train loss: 1.4441, train metric: 0.5095, valid metric: 0.4521
Epoch 40/50, train loss: 1.4274, train metric: 0.5140, valid metric: 0.4505
Epoch 41/50, train loss: 1.4117, train metric: 0.5186, valid metric: 0.4530
Epoch 42/50, train loss: 1.3954, train metric: 0.5244, valid metric: 0.4522
Epoch 43/50, train loss: 1.3823, train metric: 0.5271, valid metric: 0.4477
Epoch 44/50, train loss: 1.3691, train metric: 0.5325, valid metric: 0.4596
Epoch 45/50, train loss: 1.3531, train metric: 0.5372, valid metric: 0.4585
Epoch 46/50, train loss: 1.3412, train metric: 0.5405, valid metric: 0.4637
Epoch 47/50, train loss: 1.3267, train metric: 0.5463, valid metric: 0.4669
Epoch 48/50, train loss: 1.3142, train metric: 0.5496, valid metric: 0.4678
Epoch 49/50, train loss: 1.3026, train metric: 0.5516, valid metric: 0.4661
Epoch 50/50, train loss: 1.2887, train metric: 0.5568, valid metric: 0.4643
Best epoch: 48
Best validation accuracy: 0.4678482711315155

In [ ]:
history_2 = train(downsampling_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=20)

Epoch 1/20, train loss: 1.3017, train metric: 0.5538, valid metric: 0.4551
Epoch 2/20, train loss: 1.2875, train metric: 0.5586, valid metric: 0.4704
Epoch 3/20, train loss: 1.2755, train metric: 0.5614, valid metric: 0.4703
Epoch 4/20, train loss: 1.2633, train metric: 0.5653, valid metric: 0.4652
Epoch 5/20, train loss: 1.2516, train metric: 0.5702, valid metric: 0.4711
Epoch 6/20, train loss: 1.2419, train metric: 0.5714, valid metric: 0.4673
Epoch 7/20, train loss: 1.2271, train metric: 0.5772, valid metric: 0.4710
Epoch 8/20, train loss: 1.2204, train metric: 0.5795, valid metric: 0.4698
Epoch 9/20, train loss: 1.2054, train metric: 0.5847, valid metric: 0.4761
Epoch 10/20, train loss: 1.1967, train metric: 0.5869, valid metric: 0.4785
Epoch 11/20, train loss: 1.1841, train metric: 0.5899, valid metric: 0.4772
Epoch 12/20, train loss: 1.1750, train metric: 0.5941, valid metric: 0.4755
Epoch 13/20, train loss: 1.1624, train metric: 0.5979, valid metric: 0.4814
Epoch 14/20, train loss: 1.1530, train metric: 0.6021, valid metric: 0.4830
Epoch 15/20, train loss: 1.1443, train metric: 0.6045, valid metric: 0.4774
Epoch 16/20, train loss: 1.1350, train metric: 0.6083, valid metric: 0.4796
Epoch 17/20, train loss: 1.1243, train metric: 0.6105, valid metric: 0.4820
Epoch 18/20, train loss: 1.1147, train metric: 0.6147, valid metric: 0.4859
Epoch 19/20, train loss: 1.1051, train metric: 0.6186, valid metric: 0.4854
Epoch 20/20, train loss: 1.0941, train metric: 0.6204, valid metric: 0.4842
Best epoch: 18
Best validation accuracy: 0.48594528436660767

## Inception Models

We create an inception module: 4 parallel convolutional layers, 3 of which are a stack of two convolutional layers, with different kernel size.

The inception model stacks two inception modules and ends with two fully connected layers with dropout.

In [ ]:
from torch.nn.modules.pooling import MaxPool1d

class InceptionModule(nn.Module):
  def __init__(self, n_inputs):
    super().__init__()
    self.conv0 = nn.Sequential(
        nn.Conv1d(in_channels=n_inputs, out_channels=64, kernel_size=1, padding='same'), nn.ReLU())
    self.conv1 = nn.Sequential(
        nn.Conv1d(in_channels=n_inputs, out_channels=64, kernel_size=1, padding='same'), nn.ReLU(),
        nn.Conv1d(in_channels=64, out_channels=128, kernel_size=3, padding='same'), nn.ReLU())
    self.conv2 = nn.Sequential(
        nn.Conv1d(in_channels=n_inputs, out_channels=16, kernel_size=1, padding='same'), nn.ReLU(),
        nn.Conv1d(in_channels=16, out_channels=48, kernel_size=5, padding='same'), nn.ReLU())
    self.conv3 = nn.Sequential(
        nn.MaxPool1d(kernel_size=3, stride=1, padding=1), # stride=1, padding=1 (this depends on kernel_size=3) so the in & out have same dim
        nn.Conv1d(in_channels=n_inputs, out_channels=48, kernel_size=1, padding='same'), nn.ReLU())

  def forward(self,X):
    return torch.cat([self.conv0(X), self.conv1(X), self.conv2(X), self.conv3(X)], dim=1)

Number of output channels of the inception module:
  * 64 + 128 + 48 + 48 = 288
The spatial dimention of the 1d-convolutional layers is 100, if we do a maxpool we divide it by 2: 50.

Create a simple model with:
- inception module, maxpool
- two fully connected layers with dropout
- output layer

In [ ]:
class InceptionModel(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.incep = nn.Sequential(
      InceptionModule(n_inputs=input_size),
      nn.MaxPool1d(kernel_size=2), # this divides the height and width by 2
      InceptionModule(288),          # -> 288 channels
      nn.MaxPool1d(2)
      )
    self.output = nn.Sequential(
      nn.Flatten(),
      nn.Linear(in_features = 7200, out_features = 128), # 288 out channels, 50 spacial dimension.
      nn.ReLU(),
      nn.Dropout(0.5),
      nn.Linear(in_features = 128, out_features = 64),
      nn.ReLU(),
      nn.Dropout(0.5),
      nn.Linear(in_features = 64, out_features = output_size)
    )
    # self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    Z = X.permute(0,2,1)  # treat ticks as spatial dimension
    Z = self.incep(Z)
    return self.output(Z)

### Scaling numerical features

Before training, we scale the numerical features.

The first 9 features are numerical.

In [ ]:
num_idx = slice(0, 9)

mean = X_train[:, :, num_idx].mean(dim=(0, 1), keepdim=True)
std = X_train[:, :, num_idx].std(dim=(0, 1), keepdim=True)

X_train[:, :, num_idx] = (
    X_train[:, :, num_idx] - mean
) / (std + 1e-8)

X_val[:, :, num_idx] = (
    X_val[:, :, num_idx] - mean
) / (std + 1e-8)

In [ ]:
print(X_train[:, :, :9].mean(dim=(0,1)))
print(X_train[:, :, :9].std(dim=(0,1)))

tensor([-5.6936e-11,  1.4576e-08, -2.1624e-09, -5.0421e-08, -3.0802e-08,
        -6.9130e-09,  1.2099e-08,  9.1097e-10,  4.3879e-08])
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [ ]:
train_dataset.tensors[0] is X_train

True

In [ ]:
train_dataset.tensors[0].data_ptr() == X_train.data_ptr()

True

We scaled the tensors X_train, X_val in place and the TensorDataset references those tensors (checked above) so no need to recreate the datasets and dataloaders.

In [ ]:
torch.manual_seed(42)

incep_model = InceptionModel(input_size=20, output_size=24).to(device)

optimizer = torch.optim.NAdam(incep_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(incep_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

incep.0.conv0.0.weight 0.00020817549375351518
Epoch 1/50, train loss: 2.7901, train metric: 0.0998, valid metric: 0.1590
incep.0.conv0.0.weight 0.002215803135186434
Epoch 2/50, train loss: 2.5807, train metric: 0.1433, valid metric: 0.2000
incep.0.conv0.0.weight 0.01381155289709568
Epoch 3/50, train loss: 2.4603, train metric: 0.1882, valid metric: 0.2357
incep.0.conv0.0.weight 0.015200326219201088
Epoch 4/50, train loss: 2.3668, train metric: 0.2168, valid metric: 0.2547
incep.0.conv0.0.weight 0.016066161915659904
Epoch 5/50, train loss: 2.2923, train metric: 0.2379, valid metric: 0.2784
incep.0.conv0.0.weight 0.01758912019431591
Epoch 6/50, train loss: 2.2205, train metric: 0.2589, valid metric: 0.3007
incep.0.conv0.0.weight 0.025531558319926262
Epoch 7/50, train loss: 2.1577, train metric: 0.2775, valid metric: 0.3094
incep.0.conv0.0.weight 0.028756627812981606
Epoch 8/50, train loss: 2.1072, train metric: 0.2944, valid metric: 0.3238
incep.0.conv0.0.weight 0.03802197054028511
Epoch 9/50, train loss: 2.0601, train metric: 0.3078, valid metric: 0.3312
incep.0.conv0.0.weight 0.052906375378370285
Epoch 10/50, train loss: 2.0234, train metric: 0.3197, valid metric: 0.3426
incep.0.conv0.0.weight 0.05180766060948372
Epoch 11/50, train loss: 1.9904, train metric: 0.3290, valid metric: 0.3620
incep.0.conv0.0.weight 0.04410432651638985
Epoch 12/50, train loss: 1.9564, train metric: 0.3392, valid metric: 0.3730
incep.0.conv0.0.weight 0.03051547147333622
Epoch 13/50, train loss: 1.9262, train metric: 0.3494, valid metric: 0.3728
incep.0.conv0.0.weight 0.02270360104739666
Epoch 14/50, train loss: 1.8964, train metric: 0.3588, valid metric: 0.3900
incep.0.conv0.0.weight 0.02912071906030178
Epoch 15/50, train loss: 1.8679, train metric: 0.3658, valid metric: 0.4009
incep.0.conv0.0.weight 0.024812614545226097
Epoch 16/50, train loss: 1.8456, train metric: 0.3738, valid metric: 0.4048
incep.0.conv0.0.weight 0.03503402695059776
Epoch 17/50, train loss: 1.8166, train metric: 0.3827, valid metric: 0.4079
incep.0.conv0.0.weight 0.032958805561065674
Epoch 18/50, train loss: 1.7931, train metric: 0.3904, valid metric: 0.4129
incep.0.conv0.0.weight 0.03332846984267235
Epoch 19/50, train loss: 1.7661, train metric: 0.3964, valid metric: 0.4130
incep.0.conv0.0.weight 0.04139124974608421
Epoch 20/50, train loss: 1.7418, train metric: 0.4048, valid metric: 0.4146
incep.0.conv0.0.weight 0.03888111934065819
Epoch 21/50, train loss: 1.7193, train metric: 0.4118, valid metric: 0.4319
incep.0.conv0.0.weight 0.025313381105661392
Epoch 22/50, train loss: 1.6972, train metric: 0.4187, valid metric: 0.4324
incep.0.conv0.0.weight 0.03417663648724556
Epoch 23/50, train loss: 1.6731, train metric: 0.4250, valid metric: 0.4367
incep.0.conv0.0.weight 0.02746148221194744
Epoch 24/50, train loss: 1.6521, train metric: 0.4308, valid metric: 0.4430
incep.0.conv0.0.weight 0.025612423196434975
Epoch 25/50, train loss: 1.6369, train metric: 0.4361, valid metric: 0.4482
incep.0.conv0.0.weight 0.025720680132508278
Epoch 26/50, train loss: 1.6101, train metric: 0.4426, valid metric: 0.4492
incep.0.conv0.0.weight 0.047174520790576935
Epoch 27/50, train loss: 1.5946, train metric: 0.4476, valid metric: 0.4529
incep.0.conv0.0.weight 0.02633131481707096
Epoch 28/50, train loss: 1.5720, train metric: 0.4531, valid metric: 0.4510
incep.0.conv0.0.weight 0.04760833829641342
Epoch 29/50, train loss: 1.5533, train metric: 0.4603, valid metric: 0.4572
incep.0.conv0.0.weight 0.03268679976463318
Epoch 30/50, train loss: 1.5355, train metric: 0.4651, valid metric: 0.4577
incep.0.conv0.0.weight 0.036767810583114624
Epoch 31/50, train loss: 1.5196, train metric: 0.4698, valid metric: 0.4616
incep.0.conv0.0.weight 0.03449982404708862
Epoch 32/50, train loss: 1.5006, train metric: 0.4761, valid metric: 0.4599
incep.0.conv0.0.weight 0.03326811268925667
Epoch 33/50, train loss: 1.4834, train metric: 0.4807, valid metric: 0.4661
incep.0.conv0.0.weight 0.024060992524027824
Epoch 34/50, train loss: 1.4658, train metric: 0.4881, valid metric: 0.4615
incep.0.conv0.0.weight 0.06219511106610298
Epoch 35/50, train loss: 1.4482, train metric: 0.4916, valid metric: 0.4668
incep.0.conv0.0.weight 0.047242727130651474
Epoch 36/50, train loss: 1.4309, train metric: 0.4949, valid metric: 0.4698
incep.0.conv0.0.weight 0.02892962098121643
Epoch 37/50, train loss: 1.4140, train metric: 0.5000, valid metric: 0.4650
incep.0.conv0.0.weight 0.05133241415023804
Epoch 38/50, train loss: 1.3973, train metric: 0.5078, valid metric: 0.4630
incep.0.conv0.0.weight 0.08032633364200592
Epoch 39/50, train loss: 1.3830, train metric: 0.5102, valid metric: 0.4638
incep.0.conv0.0.weight 0.04348496347665787
Epoch 40/50, train loss: 1.3675, train metric: 0.5161, valid metric: 0.4618
incep.0.conv0.0.weight 0.04518964886665344
Epoch 41/50, train loss: 1.3549, train metric: 0.5193, valid metric: 0.4738
incep.0.conv0.0.weight 0.03917514160275459
Epoch 42/50, train loss: 1.3396, train metric: 0.5233, valid metric: 0.4717
incep.0.conv0.0.weight 0.05419569090008736
Epoch 43/50, train loss: 1.3212, train metric: 0.5274, valid metric: 0.4644
incep.0.conv0.0.weight 0.05590559169650078
Epoch 44/50, train loss: 1.3106, train metric: 0.5321, valid metric: 0.4758
incep.0.conv0.0.weight 0.03239083290100098
Epoch 45/50, train loss: 1.2983, train metric: 0.5361, valid metric: 0.4734
incep.0.conv0.0.weight 0.04111884534358978
Epoch 46/50, train loss: 1.2849, train metric: 0.5406, valid metric: 0.4732
incep.0.conv0.0.weight 0.06265238672494888
Epoch 47/50, train loss: 1.2738, train metric: 0.5436, valid metric: 0.4735
incep.0.conv0.0.weight 0.01970740035176277
Epoch 48/50, train loss: 1.2596, train metric: 0.5495, valid metric: 0.4745
incep.0.conv0.0.weight 0.03451933339238167
Epoch 49/50, train loss: 1.2476, train metric: 0.5520, valid metric: 0.4757
incep.0.conv0.0.weight 0.059627678245306015
Epoch 50/50, train loss: 1.2374, train metric: 0.5562, valid metric: 0.4737
Best epoch: 44
Best validation accuracy: 0.47577735781669617

### Inception Model 2 (with avg pooling)

Add a average pooling layer over the 'ticks-dimension' (which is already reduced to 25) before the final dense classification layers.

We lose **where** in the sequence the pattern occurred. Only retain something like "how strongly this feature occurred overall."

In [ ]:
class InceptionModel2(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.incep = nn.Sequential(
      InceptionModule(n_inputs=input_size),
      nn.MaxPool1d(kernel_size=2), # this divides the height and width by 2
      InceptionModule(288),          # -> 288 channels
      nn.MaxPool1d(2)
      )
    self.pool = nn.AdaptiveAvgPool1d(1)
    self.output = nn.Sequential(
      nn.Linear(in_features = 288, out_features = 128), # 288 out channels
      nn.ReLU(),
      nn.Dropout(0.5),
      nn.Linear(in_features = 128, out_features = output_size),
    )

  def forward(self,X):
    Z = X.permute(0,2,1)  # treat ticks as spatial dimension
    Z = self.incep(Z)     # (B, 288, 25)
    Z = self.pool(Z)      # (B, 288, 1)
    Z = Z.squeeze(-1)     # (B, 288)
    return self.output(Z)

In [ ]:
torch.manual_seed(42)

incep_model2 = InceptionModel2(input_size=20, output_size=24).to(device)

optimizer = torch.optim.NAdam(incep_model2.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(incep_model2, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.7032, train metric: 0.1226, valid metric: 0.2050
Epoch 2/50, train loss: 2.4532, train metric: 0.1943, valid metric: 0.2280
Epoch 3/50, train loss: 2.3629, train metric: 0.2227, valid metric: 0.2541
Epoch 4/50, train loss: 2.2929, train metric: 0.2448, valid metric: 0.2763
Epoch 5/50, train loss: 2.2377, train metric: 0.2633, valid metric: 0.2905
Epoch 6/50, train loss: 2.1880, train metric: 0.2790, valid metric: 0.3056
Epoch 7/50, train loss: 2.1414, train metric: 0.2911, valid metric: 0.3140
Epoch 8/50, train loss: 2.0977, train metric: 0.3043, valid metric: 0.3312
Epoch 9/50, train loss: 2.0597, train metric: 0.3148, valid metric: 0.3312
Epoch 10/50, train loss: 2.0237, train metric: 0.3242, valid metric: 0.3500
Epoch 11/50, train loss: 1.9919, train metric: 0.3330, valid metric: 0.3573
Epoch 12/50, train loss: 1.9633, train metric: 0.3421, valid metric: 0.3649
Epoch 13/50, train loss: 1.9365, train metric: 0.3497, valid metric: 0.3670
Epoch 14/50, train loss: 1.9105, train metric: 0.3576, valid metric: 0.3771
Epoch 15/50, train loss: 1.8865, train metric: 0.3663, valid metric: 0.3883
Epoch 16/50, train loss: 1.8677, train metric: 0.3712, valid metric: 0.3852
Epoch 17/50, train loss: 1.8470, train metric: 0.3786, valid metric: 0.3953
Epoch 18/50, train loss: 1.8276, train metric: 0.3850, valid metric: 0.4111
Epoch 19/50, train loss: 1.8091, train metric: 0.3903, valid metric: 0.4155
Epoch 20/50, train loss: 1.7901, train metric: 0.3984, valid metric: 0.4220
Epoch 21/50, train loss: 1.7697, train metric: 0.4026, valid metric: 0.4235
Epoch 22/50, train loss: 1.7550, train metric: 0.4077, valid metric: 0.4345
Epoch 23/50, train loss: 1.7360, train metric: 0.4148, valid metric: 0.4417
Epoch 24/50, train loss: 1.7225, train metric: 0.4186, valid metric: 0.4457
Epoch 25/50, train loss: 1.7037, train metric: 0.4256, valid metric: 0.4390
Epoch 26/50, train loss: 1.6856, train metric: 0.4313, valid metric: 0.4596
Epoch 27/50, train loss: 1.6722, train metric: 0.4333, valid metric: 0.4576
Epoch 28/50, train loss: 1.6561, train metric: 0.4392, valid metric: 0.4654
Epoch 29/50, train loss: 1.6426, train metric: 0.4458, valid metric: 0.4676
Epoch 30/50, train loss: 1.6269, train metric: 0.4483, valid metric: 0.4749
Epoch 31/50, train loss: 1.6128, train metric: 0.4550, valid metric: 0.4794
Epoch 32/50, train loss: 1.5995, train metric: 0.4582, valid metric: 0.4857
Epoch 33/50, train loss: 1.5867, train metric: 0.4632, valid metric: 0.4765
Epoch 34/50, train loss: 1.5725, train metric: 0.4681, valid metric: 0.4912
Epoch 35/50, train loss: 1.5598, train metric: 0.4717, valid metric: 0.4973
Epoch 36/50, train loss: 1.5476, train metric: 0.4759, valid metric: 0.5021
Epoch 37/50, train loss: 1.5310, train metric: 0.4799, valid metric: 0.5065
Epoch 38/50, train loss: 1.5209, train metric: 0.4842, valid metric: 0.5051
Epoch 39/50, train loss: 1.5095, train metric: 0.4886, valid metric: 0.5141
Epoch 40/50, train loss: 1.4980, train metric: 0.4912, valid metric: 0.5163
Epoch 41/50, train loss: 1.4863, train metric: 0.4970, valid metric: 0.5065
Epoch 42/50, train loss: 1.4767, train metric: 0.4998, valid metric: 0.5234
Epoch 43/50, train loss: 1.4635, train metric: 0.5045, valid metric: 0.5197
Epoch 44/50, train loss: 1.4564, train metric: 0.5045, valid metric: 0.5315
Epoch 45/50, train loss: 1.4431, train metric: 0.5096, valid metric: 0.5280
Epoch 46/50, train loss: 1.4333, train metric: 0.5143, valid metric: 0.5365
Epoch 47/50, train loss: 1.4240, train metric: 0.5150, valid metric: 0.5417
Epoch 48/50, train loss: 1.4116, train metric: 0.5197, valid metric: 0.5342
Epoch 49/50, train loss: 1.4039, train metric: 0.5235, valid metric: 0.5428
Epoch 50/50, train loss: 1.3947, train metric: 0.5269, valid metric: 0.5497
Best epoch: 50
Best validation accuracy: 0.5497201681137085

In [ ]:
history_2 = train(incep_model2, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=20)

Epoch 1/20, train loss: 1.3834, train metric: 0.5293, valid metric: 0.5391
Epoch 2/20, train loss: 1.3747, train metric: 0.5321, valid metric: 0.5549
Epoch 3/20, train loss: 1.3658, train metric: 0.5339, valid metric: 0.5577
Epoch 4/20, train loss: 1.3581, train metric: 0.5382, valid metric: 0.5650
Epoch 5/20, train loss: 1.3474, train metric: 0.5406, valid metric: 0.5540
Epoch 6/20, train loss: 1.3386, train metric: 0.5457, valid metric: 0.5673
Epoch 7/20, train loss: 1.3302, train metric: 0.5481, valid metric: 0.5715
Epoch 8/20, train loss: 1.3202, train metric: 0.5495, valid metric: 0.5677
Epoch 9/20, train loss: 1.3136, train metric: 0.5524, valid metric: 0.5749
Epoch 10/20, train loss: 1.3059, train metric: 0.5533, valid metric: 0.5675
Epoch 11/20, train loss: 1.2942, train metric: 0.5585, valid metric: 0.5737
Epoch 12/20, train loss: 1.2881, train metric: 0.5596, valid metric: 0.5780
Epoch 13/20, train loss: 1.2844, train metric: 0.5625, valid metric: 0.5721
Epoch 14/20, train loss: 1.2739, train metric: 0.5664, valid metric: 0.5787
Epoch 15/20, train loss: 1.2673, train metric: 0.5675, valid metric: 0.5834
Epoch 16/20, train loss: 1.2583, train metric: 0.5703, valid metric: 0.5811
Epoch 17/20, train loss: 1.2521, train metric: 0.5726, valid metric: 0.5931
Epoch 18/20, train loss: 1.2435, train metric: 0.5754, valid metric: 0.5925
Epoch 19/20, train loss: 1.2383, train metric: 0.5775, valid metric: 0.5994
Epoch 20/20, train loss: 1.2315, train metric: 0.5785, valid metric: 0.5989
Best epoch: 19
Best validation accuracy: 0.5994092226028442

In [ ]:
history_3 = train(incep_model2, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 1.2313, train metric: 0.5797, valid metric: 0.5996
Epoch 2/50, train loss: 1.2215, train metric: 0.5823, valid metric: 0.6008
Epoch 3/50, train loss: 1.2169, train metric: 0.5827, valid metric: 0.6007
Epoch 4/50, train loss: 1.2095, train metric: 0.5862, valid metric: 0.5937
Epoch 5/50, train loss: 1.1997, train metric: 0.5903, valid metric: 0.6069
Epoch 6/50, train loss: 1.1976, train metric: 0.5902, valid metric: 0.6078
Epoch 7/50, train loss: 1.1880, train metric: 0.5938, valid metric: 0.6098
Epoch 8/50, train loss: 1.1818, train metric: 0.5949, valid metric: 0.6050
Epoch 9/50, train loss: 1.1768, train metric: 0.5969, valid metric: 0.6091
Epoch 10/50, train loss: 1.1667, train metric: 0.5997, valid metric: 0.6160
Epoch 11/50, train loss: 1.1602, train metric: 0.6013, valid metric: 0.6093
Epoch 12/50, train loss: 1.1556, train metric: 0.6053, valid metric: 0.6157
Epoch 13/50, train loss: 1.1505, train metric: 0.6063, valid metric: 0.6192
Epoch 14/50, train loss: 1.1441, train metric: 0.6073, valid metric: 0.6210
Epoch 15/50, train loss: 1.1393, train metric: 0.6087, valid metric: 0.6188
Epoch 16/50, train loss: 1.1322, train metric: 0.6110, valid metric: 0.6235
Epoch 17/50, train loss: 1.1285, train metric: 0.6122, valid metric: 0.6198
Epoch 18/50, train loss: 1.1229, train metric: 0.6139, valid metric: 0.6198
Epoch 19/50, train loss: 1.1126, train metric: 0.6185, valid metric: 0.6189
Epoch 20/50, train loss: 1.1091, train metric: 0.6192, valid metric: 0.6278
Epoch 21/50, train loss: 1.1038, train metric: 0.6203, valid metric: 0.6201
Epoch 22/50, train loss: 1.0986, train metric: 0.6233, valid metric: 0.6274
Epoch 23/50, train loss: 1.0953, train metric: 0.6239, valid metric: 0.6304
Epoch 24/50, train loss: 1.0885, train metric: 0.6257, valid metric: 0.6310
Epoch 25/50, train loss: 1.0836, train metric: 0.6276, valid metric: 0.6250
Epoch 26/50, train loss: 1.0794, train metric: 0.6289, valid metric: 0.6271
Epoch 27/50, train loss: 1.0734, train metric: 0.6299, valid metric: 0.6321
Epoch 28/50, train loss: 1.0702, train metric: 0.6326, valid metric: 0.6324
Epoch 29/50, train loss: 1.0669, train metric: 0.6322, valid metric: 0.6332
Epoch 30/50, train loss: 1.0620, train metric: 0.6340, valid metric: 0.6389
Epoch 31/50, train loss: 1.0548, train metric: 0.6357, valid metric: 0.6336
Epoch 32/50, train loss: 1.0516, train metric: 0.6369, valid metric: 0.6374
Epoch 33/50, train loss: 1.0467, train metric: 0.6402, valid metric: 0.6404
Epoch 34/50, train loss: 1.0400, train metric: 0.6404, valid metric: 0.6353
Epoch 35/50, train loss: 1.0385, train metric: 0.6418, valid metric: 0.6424
Epoch 36/50, train loss: 1.0327, train metric: 0.6427, valid metric: 0.6396
Epoch 37/50, train loss: 1.0294, train metric: 0.6441, valid metric: 0.6331
Epoch 38/50, train loss: 1.0246, train metric: 0.6459, valid metric: 0.6461
Epoch 39/50, train loss: 1.0182, train metric: 0.6468, valid metric: 0.6451
Epoch 40/50, train loss: 1.0154, train metric: 0.6488, valid metric: 0.6468
Epoch 41/50, train loss: 1.0125, train metric: 0.6500, valid metric: 0.6455
Epoch 42/50, train loss: 1.0076, train metric: 0.6514, valid metric: 0.6445
Epoch 43/50, train loss: 1.0048, train metric: 0.6517, valid metric: 0.6476
Epoch 44/50, train loss: 0.9980, train metric: 0.6539, valid metric: 0.6476
Epoch 45/50, train loss: 0.9962, train metric: 0.6553, valid metric: 0.6398
Epoch 46/50, train loss: 0.9940, train metric: 0.6557, valid metric: 0.6443
Epoch 47/50, train loss: 0.9871, train metric: 0.6577, valid metric: 0.6506
Epoch 48/50, train loss: 0.9844, train metric: 0.6578, valid metric: 0.6441
Epoch 49/50, train loss: 0.9812, train metric: 0.6595, valid metric: 0.6516
Epoch 50/50, train loss: 0.9751, train metric: 0.6614, valid metric: 0.6465
Best epoch: 49
Best validation accuracy: 0.6516169309616089

### Inception Model with GRU

Inception Module stacked with Gru Module.

In [ ]:
class InceptionGRUModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.incep = nn.Sequential(
      InceptionModule(n_inputs=input_size),
      nn.MaxPool1d(kernel_size=2), # this divides the height and width by 2
      InceptionModule(288),          # -> 288 channels
      nn.MaxPool1d(2)
      )
    self.gru = nn.GRU(
      input_size=288,
      hidden_size=hidden_size,
      num_layers=2,
      batch_first=True
      )
    self.output = nn.Linear(in_features = hidden_size, out_features = output_size)

  def forward(self,X):
    Z = X.permute(0,2,1)  # treat ticks as spatial dimension
    Z = self.incep(Z)     # (B, 288, 25)
    Z = Z.permute(0, 2, 1) # (B, 25, 288)

    outputs, _ = self.gru(Z)
    return self.output(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

incep_gru_model = InceptionGRUModel(input_size=20, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(incep_gru_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(incep_gru_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.5671, train metric: 0.1538, valid metric: 0.2123
Epoch 2/50, train loss: 2.2725, train metric: 0.2495, valid metric: 0.2759
Epoch 3/50, train loss: 2.1124, train metric: 0.2991, valid metric: 0.2989
Epoch 4/50, train loss: 1.9979, train metric: 0.3328, valid metric: 0.3364
Epoch 5/50, train loss: 1.9105, train metric: 0.3585, valid metric: 0.3604
Epoch 6/50, train loss: 1.8396, train metric: 0.3795, valid metric: 0.3783
Epoch 7/50, train loss: 1.7777, train metric: 0.3988, valid metric: 0.3905
Epoch 8/50, train loss: 1.7195, train metric: 0.4172, valid metric: 0.4034
Epoch 9/50, train loss: 1.6675, train metric: 0.4342, valid metric: 0.4265
Epoch 10/50, train loss: 1.6207, train metric: 0.4488, valid metric: 0.4412
Epoch 11/50, train loss: 1.5771, train metric: 0.4626, valid metric: 0.4525
Epoch 12/50, train loss: 1.5365, train metric: 0.4767, valid metric: 0.4674
Epoch 13/50, train loss: 1.4971, train metric: 0.4873, valid metric: 0.4682
Epoch 14/50, train loss: 1.4613, train metric: 0.5005, valid metric: 0.4812
Epoch 15/50, train loss: 1.4277, train metric: 0.5118, valid metric: 0.4919
Epoch 16/50, train loss: 1.3951, train metric: 0.5225, valid metric: 0.5073
Epoch 17/50, train loss: 1.3643, train metric: 0.5315, valid metric: 0.5076
Epoch 18/50, train loss: 1.3356, train metric: 0.5423, valid metric: 0.5155
Epoch 19/50, train loss: 1.3090, train metric: 0.5510, valid metric: 0.5282
Epoch 20/50, train loss: 1.2823, train metric: 0.5603, valid metric: 0.5340
Epoch 21/50, train loss: 1.2580, train metric: 0.5672, valid metric: 0.5369
Epoch 22/50, train loss: 1.2350, train metric: 0.5751, valid metric: 0.5324
Epoch 23/50, train loss: 1.2119, train metric: 0.5830, valid metric: 0.5479
Epoch 24/50, train loss: 1.1897, train metric: 0.5912, valid metric: 0.5550
Epoch 25/50, train loss: 1.1697, train metric: 0.5966, valid metric: 0.5650
Epoch 26/50, train loss: 1.1483, train metric: 0.6049, valid metric: 0.5735
Epoch 27/50, train loss: 1.1284, train metric: 0.6110, valid metric: 0.5648
Epoch 28/50, train loss: 1.1069, train metric: 0.6177, valid metric: 0.5683
Epoch 29/50, train loss: 1.0874, train metric: 0.6244, valid metric: 0.5664
Epoch 30/50, train loss: 1.0691, train metric: 0.6308, valid metric: 0.5853
Epoch 31/50, train loss: 1.0502, train metric: 0.6374, valid metric: 0.5840
Epoch 32/50, train loss: 1.0316, train metric: 0.6430, valid metric: 0.5740
Epoch 33/50, train loss: 1.0144, train metric: 0.6478, valid metric: 0.5892
Epoch 34/50, train loss: 0.9970, train metric: 0.6540, valid metric: 0.5944
Epoch 35/50, train loss: 0.9780, train metric: 0.6611, valid metric: 0.5974
Epoch 36/50, train loss: 0.9603, train metric: 0.6678, valid metric: 0.6065
Epoch 37/50, train loss: 0.9437, train metric: 0.6718, valid metric: 0.5741
Epoch 38/50, train loss: 0.9269, train metric: 0.6787, valid metric: 0.6075
Epoch 39/50, train loss: 0.9113, train metric: 0.6827, valid metric: 0.6104
Epoch 40/50, train loss: 0.8938, train metric: 0.6902, valid metric: 0.6107
Epoch 41/50, train loss: 0.8769, train metric: 0.6953, valid metric: 0.6071
Epoch 42/50, train loss: 0.8622, train metric: 0.6996, valid metric: 0.6128
Epoch 43/50, train loss: 0.8463, train metric: 0.7056, valid metric: 0.6190
Epoch 44/50, train loss: 0.8304, train metric: 0.7099, valid metric: 0.6157
Epoch 45/50, train loss: 0.8148, train metric: 0.7173, valid metric: 0.6072
Epoch 46/50, train loss: 0.7998, train metric: 0.7202, valid metric: 0.6223
Epoch 47/50, train loss: 0.7844, train metric: 0.7257, valid metric: 0.6224
Epoch 48/50, train loss: 0.7689, train metric: 0.7323, valid metric: 0.6252
Epoch 49/50, train loss: 0.7548, train metric: 0.7357, valid metric: 0.6221
Epoch 50/50, train loss: 0.7398, train metric: 0.7420, valid metric: 0.6275
Best epoch: 50
Best validation accuracy: 0.6275497674942017

In [ ]:
history2 = train(incep_gru_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 0.7272, train metric: 0.7459, valid metric: 0.6220
Epoch 2/50, train loss: 0.7123, train metric: 0.7519, valid metric: 0.6320
Epoch 3/50, train loss: 0.6982, train metric: 0.7564, valid metric: 0.6273
Epoch 4/50, train loss: 0.6861, train metric: 0.7595, valid metric: 0.6310
Epoch 5/50, train loss: 0.6708, train metric: 0.7651, valid metric: 0.6259
Epoch 6/50, train loss: 0.6573, train metric: 0.7701, valid metric: 0.6258
Epoch 7/50, train loss: 0.6450, train metric: 0.7753, valid metric: 0.6326
Epoch 8/50, train loss: 0.6329, train metric: 0.7778, valid metric: 0.6322
Epoch 9/50, train loss: 0.6200, train metric: 0.7832, valid metric: 0.6352
Epoch 10/50, train loss: 0.6077, train metric: 0.7871, valid metric: 0.6285
Epoch 11/50, train loss: 0.5929, train metric: 0.7936, valid metric: 0.6338
Epoch 12/50, train loss: 0.5806, train metric: 0.7971, valid metric: 0.6338
Epoch 13/50, train loss: 0.5704, train metric: 0.8003, valid metric: 0.6359
Epoch 14/50, train loss: 0.5574, train metric: 0.8052, valid metric: 0.6282
Epoch 15/50, train loss: 0.5459, train metric: 0.8096, valid metric: 0.6260
Epoch 16/50, train loss: 0.5350, train metric: 0.8136, valid metric: 0.6323
Epoch 17/50, train loss: 0.5227, train metric: 0.8182, valid metric: 0.6338
Epoch 18/50, train loss: 0.5113, train metric: 0.8216, valid metric: 0.6267
Epoch 19/50, train loss: 0.5003, train metric: 0.8258, valid metric: 0.6346

KeyboardInterrupt:

Stopped training as it was starting to overfit.

Best accuracy around a total of 60 epochs: 63%.

## Parallel GRU + Inception

Inception Model 2 and Deep GRU Model achieve similar accuracy after 60-70 epochs, while stacking a gru on top of inception gets to a high accuracy but starts to overfit early.

So we try to run them in parallel, instead of stacking them.

After the inception modules we do an average pooling and reduce the ticks dimension (which is 25 after the two inceptions) to 1. We could try using Max instead of Average.

In [ ]:
class ParallelInceptionGRUModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()

    self.incep = nn.Sequential(
      InceptionModule(n_inputs=input_size),
      nn.MaxPool1d(kernel_size=2), # this divides the height and width by 2
      InceptionModule(288),          # -> 288 channels
      nn.MaxPool1d(2)
      )

    self.pool = nn.AdaptiveAvgPool1d(1) # could do nn.AdaptiveMaxPool1d(1)

    self.gru = nn.GRU(
      input_size=input_size,
      hidden_size=hidden_size,
      num_layers=2,
      batch_first=True
      )

    self.output = nn.Linear(
            hidden_size + 288,
            output_size
            )

    # alternative:
    '''
    self.output = nn.Sequential(
      nn.Linear(hidden_size + 288, 128),
      nn.ReLU(),
      nn.Dropout(0.3),
      nn.Linear(128, 24)
      )
    '''


  def forward(self,X):
    # inception output
    Z = X.permute(0,2,1)  # treat ticks as spatial dimension
    Z = self.incep(Z)     # (B, 288, 25)
    Z = self.pool(Z)      # (B, 288, 1)
    incep_out = Z.squeeze(-1)     # (B, 288)

    # gru output
    outputs, _ = self.gru(X)
    gru_out = outputs[:, -1] # (B, hidden_size)

    # combine outputs
    Z = torch.cat([gru_out, incep_out], dim=1)

    return self.output(Z)

In [ ]:
torch.manual_seed(42)

parallel_model = ParallelInceptionGRUModel(input_size=20, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(parallel_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(parallel_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.5744, train metric: 0.1728, valid metric: 0.2294
Epoch 2/50, train loss: 2.3368, train metric: 0.2468, valid metric: 0.2634
Epoch 3/50, train loss: 2.2224, train metric: 0.2797, valid metric: 0.2887
Epoch 4/50, train loss: 2.1428, train metric: 0.3021, valid metric: 0.3146
Epoch 5/50, train loss: 2.0791, train metric: 0.3197, valid metric: 0.3261
Epoch 6/50, train loss: 2.0224, train metric: 0.3387, valid metric: 0.3433
Epoch 7/50, train loss: 1.9613, train metric: 0.3569, valid metric: 0.3657
Epoch 8/50, train loss: 1.8964, train metric: 0.3783, valid metric: 0.3773
Epoch 9/50, train loss: 1.8428, train metric: 0.3947, valid metric: 0.3928
Epoch 10/50, train loss: 1.7982, train metric: 0.4080, valid metric: 0.4070
Epoch 11/50, train loss: 1.7598, train metric: 0.4196, valid metric: 0.4102
Epoch 12/50, train loss: 1.7244, train metric: 0.4303, valid metric: 0.4289
Epoch 13/50, train loss: 1.6934, train metric: 0.4396, valid metric: 0.4354
Epoch 14/50, train loss: 1.6639, train metric: 0.4477, valid metric: 0.4413
Epoch 15/50, train loss: 1.6376, train metric: 0.4558, valid metric: 0.4439
Epoch 16/50, train loss: 1.6136, train metric: 0.4630, valid metric: 0.4569
Epoch 17/50, train loss: 1.5891, train metric: 0.4705, valid metric: 0.4630
Epoch 18/50, train loss: 1.5672, train metric: 0.4763, valid metric: 0.4644
Epoch 19/50, train loss: 1.5462, train metric: 0.4821, valid metric: 0.4750
Epoch 20/50, train loss: 1.5255, train metric: 0.4897, valid metric: 0.4806
Epoch 21/50, train loss: 1.5037, train metric: 0.4957, valid metric: 0.4890
Epoch 22/50, train loss: 1.4854, train metric: 0.5016, valid metric: 0.4896
Epoch 23/50, train loss: 1.4664, train metric: 0.5070, valid metric: 0.4924
Epoch 24/50, train loss: 1.4484, train metric: 0.5133, valid metric: 0.4953
Epoch 25/50, train loss: 1.4303, train metric: 0.5186, valid metric: 0.5050
Epoch 26/50, train loss: 1.4139, train metric: 0.5239, valid metric: 0.5106
Epoch 27/50, train loss: 1.3969, train metric: 0.5286, valid metric: 0.5170
Epoch 28/50, train loss: 1.3801, train metric: 0.5360, valid metric: 0.5173
Epoch 29/50, train loss: 1.3642, train metric: 0.5399, valid metric: 0.5186
Epoch 30/50, train loss: 1.3490, train metric: 0.5453, valid metric: 0.5252
Epoch 31/50, train loss: 1.3323, train metric: 0.5500, valid metric: 0.5267
Epoch 32/50, train loss: 1.3177, train metric: 0.5547, valid metric: 0.5317
Epoch 33/50, train loss: 1.3026, train metric: 0.5611, valid metric: 0.5361
Epoch 34/50, train loss: 1.2872, train metric: 0.5646, valid metric: 0.5367
Epoch 35/50, train loss: 1.2736, train metric: 0.5700, valid metric: 0.5377
Epoch 36/50, train loss: 1.2595, train metric: 0.5732, valid metric: 0.5451
Epoch 37/50, train loss: 1.2454, train metric: 0.5791, valid metric: 0.5447
Epoch 38/50, train loss: 1.2305, train metric: 0.5832, valid metric: 0.5505
Epoch 39/50, train loss: 1.2173, train metric: 0.5874, valid metric: 0.5458
Epoch 40/50, train loss: 1.2047, train metric: 0.5911, valid metric: 0.5498
Epoch 41/50, train loss: 1.1907, train metric: 0.5974, valid metric: 0.5597
Epoch 42/50, train loss: 1.1772, train metric: 0.6014, valid metric: 0.5574
Epoch 43/50, train loss: 1.1646, train metric: 0.6048, valid metric: 0.5578
Epoch 44/50, train loss: 1.1519, train metric: 0.6097, valid metric: 0.5643
Epoch 45/50, train loss: 1.1389, train metric: 0.6120, valid metric: 0.5662
Epoch 46/50, train loss: 1.1261, train metric: 0.6180, valid metric: 0.5674
Epoch 47/50, train loss: 1.1141, train metric: 0.6225, valid metric: 0.5701
Epoch 48/50, train loss: 1.1021, train metric: 0.6260, valid metric: 0.5746
Epoch 49/50, train loss: 1.0907, train metric: 0.6292, valid metric: 0.5746
Epoch 50/50, train loss: 1.0775, train metric: 0.6338, valid metric: 0.5713
Best epoch: 49
Best validation accuracy: 0.5745957493782043

In [ ]:
history_2 = train(parallel_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=20)

Epoch 1/20, train loss: 1.0769, train metric: 0.6341, valid metric: 0.5719
Epoch 2/20, train loss: 1.0652, train metric: 0.6378, valid metric: 0.5719
Epoch 3/20, train loss: 1.0533, train metric: 0.6421, valid metric: 0.5822
Epoch 4/20, train loss: 1.0420, train metric: 0.6479, valid metric: 0.5768
Epoch 5/20, train loss: 1.0288, train metric: 0.6504, valid metric: 0.5815
Epoch 6/20, train loss: 1.0171, train metric: 0.6550, valid metric: 0.5847
Epoch 7/20, train loss: 1.0058, train metric: 0.6572, valid metric: 0.5870
Epoch 8/20, train loss: 0.9931, train metric: 0.6630, valid metric: 0.5904
Epoch 9/20, train loss: 0.9815, train metric: 0.6665, valid metric: 0.5808
Epoch 10/20, train loss: 0.9701, train metric: 0.6708, valid metric: 0.5836
Epoch 11/20, train loss: 0.9588, train metric: 0.6750, valid metric: 0.5910
Epoch 12/20, train loss: 0.9471, train metric: 0.6779, valid metric: 0.5909
Epoch 13/20, train loss: 0.9365, train metric: 0.6820, valid metric: 0.5909
Epoch 14/20, train loss: 0.9249, train metric: 0.6858, valid metric: 0.5859
Epoch 15/20, train loss: 0.9150, train metric: 0.6887, valid metric: 0.5956
Epoch 16/20, train loss: 0.9032, train metric: 0.6924, valid metric: 0.5959
Epoch 17/20, train loss: 0.8941, train metric: 0.6956, valid metric: 0.5929
Epoch 18/20, train loss: 0.8832, train metric: 0.6986, valid metric: 0.5961
Epoch 19/20, train loss: 0.8732, train metric: 0.7040, valid metric: 0.5944
Epoch 20/20, train loss: 0.8630, train metric: 0.7071, valid metric: 0.5997
Best epoch: 20
Best validation accuracy: 0.5996579527854919