<a href="https://colab.research.google.com/github/lricci03/challengedata/blob/main/CFM2024-new/cfm2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CFM 2024 Datachallenge

Models:
* Simple RNN, 1-layer GRU, 1-layer LSTM, simplified WaveNet
* 2-layers GRU (Deep GRU Model): trained for 60 epochs, validation accuracy 61%.

In [1]:
import torch
import torch.nn as nn

if torch.cuda.is_available():
  device = 'cuda'
elif torch.backends.mps.is_available():
  device = 'mps'
else:
  device = 'cpu'

In [2]:
import pandas as pd

In [3]:
from google.colab import drive

# drive.flush_and_unmount()
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [4]:
from pathlib import Path

DATA_DIR = Path(
    "/content/drive/MyDrive/Challengedata"
)

print(DATA_DIR.exists())

True

The original csv file is 1.2GB. Locally in CSV we convert it into a parquet file

```
import duckdb

# convert X_train_N1UvY30.csv into Xtrain.parquet
duckdb.sql("""
COPY (
    SELECT *
    FROM read_csv_auto('../X_train_N1UvY30.csv')
)
TO 'Xtrain.parquet'
(FORMAT PARQUET, COMPRESSION ZSTD);
""")
```

Upload the data in a dataframe and look at the first 10 rows.

In [5]:
path = Path("/content/drive/MyDrive/Challengedata/Xtrain.parquet")

df_features = pd.read_parquet(path)

df_features.head()

,obs_id,venue,order_id,action,side,price,bid,ask,bid_size,ask_size,trade,flux
0,0,4,0,A,A,0.30,0.0,0.01,100,1,False,100
1,0,4,1,A,B,-0.17,0.0,0.01,100,1,False,100
2,0,4,2,D,A,0.28,0.0,0.01,100,1,False,-100
3,0,4,3,A,A,0.30,0.0,0.01,100,1,False,100
4,0,4,4,D,A,0.37,0.0,0.01,100,1,False,-100

In [6]:
df_features.shape

(16080000, 12)

In [7]:
df_features.columns

Index(['obs_id', 'venue', 'order_id', 'action', 'side', 'price', 'bid', 'ask',
       'bid_size', 'ask_size', 'trade', 'flux'],
      dtype='object')

Upload the targets

In [8]:
df_targets = pd.read_csv("/content/drive/MyDrive/Challengedata/y_train_or6m3Ta.csv")

df_targets.head()

   obs_id  eqt_code_cat
0       0            10
1       1            15
2       2             0
3       3            13
4       4             0

`order_id` are too many for one-hot encoding and most importantly it is preserved across observations.

We extract two informations out of it:
- order_seen_before
- order_previous_count

Since we want to create these features as well for the test set later on, we define a function that does it.

In [9]:
def add_order_features(df):

    # how many previous events involved this same order
    df["order_previous_count"] = (
        df.groupby(["obs_id", "order_id"])
          .cumcount()
          .astype("float32")
    )

    # whether this order was seen before
    df["order_seen_before"] = (
        df["order_previous_count"] > 0
    ).astype("float32")

    # raw ID no longer needed
    df.drop("order_id", axis=1, inplace=True)

    return df

In [10]:
df_features = add_order_features(df_features)

One-hot-encoding

In [11]:
df_features = df_features[[
    "obs_id",
    "price", "bid", "ask",
    "bid_size", "ask_size",
    "flux",
    "action", "venue", "side", "trade",
    "order_previous_count",
    "order_seen_before"
]]

In [12]:
num_attribs = ['price', 'bid', 'ask', 'bid_size', 'ask_size', 'flux', 'trade', 'order_seen_before', 'order_previous_count']
cat_attribs = ['venue', 'action', 'side']

In [13]:
df_features[num_attribs] = df_features[num_attribs].astype("float32")

In [14]:
df_features = pd.get_dummies(df_features, columns=cat_attribs, dtype="float32")

## Train and Validation Split

In [15]:
df_features = df_features.set_index("obs_id")
df_targets = df_targets.set_index("obs_id")

In [16]:
from sklearn.model_selection import train_test_split

train_ids, val_ids = train_test_split(
    df_targets.index,
    test_size=0.2,
    random_state=42
)

In [17]:
X_train = df_features.loc[train_ids]
X_val   = df_features.loc[val_ids]

y_train = df_targets.loc[train_ids]
y_val   = df_targets.loc[val_ids]

In [18]:
print(df_features.isna().sum())

price                   0
bid                     0
ask                     0
bid_size                0
ask_size                0
flux                    0
trade                   0
order_previous_count    0
order_seen_before       0
venue_0                 0
venue_1                 0
venue_2                 0
venue_3                 0
venue_4                 0
venue_5                 0
action_A                0
action_D                0
action_U                0
side_A                  0
side_B                  0
dtype: int64

## Convert to tensors

Number of features

In [19]:
n_features = X_train.shape[1]

print(n_features)

20

In [20]:
# Reshape X. This reinterprets every consecutive block of 100 rows as one sample.
# The *-1* means: infer this dimension automatically

X_train = torch.tensor(
    X_train.to_numpy(),
    dtype=torch.float32
).reshape(-1, 100, n_features)

X_val = torch.tensor(
    X_val.to_numpy(),
    dtype=torch.float32
).reshape(-1, 100, n_features)

# For classification, the targets should be integers, not floats -> `dtype=torch.long`

y_train = torch.tensor(
    y_train["eqt_code_cat"].to_numpy(),
    dtype=torch.long
)

y_val = torch.tensor(
    y_val["eqt_code_cat"].to_numpy(),
    dtype=torch.long
)

In [21]:
print(torch.isnan(X_train).any())
print(torch.isnan(X_val).any())

tensor(False)
tensor(False)

Delete the dataframes

In [22]:
import gc

del df_features, df_targets
gc.collect()

0

In [23]:
print("train_set shape:", X_train.shape)
print("y_train shape:", y_train.shape)

train_set shape: torch.Size([128640, 100, 20])
y_train shape: torch.Size([128640])

## Dataset and Dataloader

This is not needed if we already reshaped X. We can just use TensorDataset.

In [27]:
class StockDataset(torch.utils.data.Dataset):
  def __init__(self, features, targets):
    self.features = features
    self.targets = targets

  def __len__(self):
    return len(self.targets) # number of samples

  def __getitem__(self, idx):
    window = self.features[100* idx: 100*(idx + 1)]
    target = self.targets[idx]
    return window, target

In [24]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [25]:
valid_dataset = TensorDataset(X_val, y_val)
valid_loader = DataLoader(valid_dataset, batch_size=32)

Shape of dataset features and shape of dataset output

In [26]:
train_dataset[0][0].shape, train_dataset[0][1].shape

(torch.Size([100, 20]), torch.Size([]))

The shape of the target is a scalar, which is correct for `CrossEntropyLoss` when we do a classification problem.

## Train and evaluation functions

In [27]:
%pip install -q torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 11.6 MB/s eta 0:00:00

In [28]:
import torchmetrics
import copy

def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)

            y_class = y_pred.argmax(dim=1)
            metric.update(y_class, y_batch)
    return metric.compute()

def train(model, optimizer, loss_fn, metric, train_loader, valid_loader,
          n_epochs, patience=20, factor=0.1):

    best_valid = -float("inf")
    best_model_state = None
    best_epoch = None

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max", # we monitor accuracy
        patience=patience,
        factor=factor)
    history = {"train_losses": [], "train_metrics": [], "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.0
        metric.reset()
        model.train()
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            loss = loss_fn(y_pred, y_batch)

            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

            y_class = y_pred.detach().argmax(dim=1)
            metric.update(y_class, y_batch)

        train_loss = total_loss / len(train_loader)
        train_metric = metric.compute().item()
        val_metric = evaluate_tm(model, valid_loader, metric).item()

        if val_metric > best_valid:
          best_valid = val_metric
          best_model_state = copy.deepcopy(model.state_dict())
          best_epoch = epoch +1 # +1 bc epoch starts at 0

        history["train_losses"].append(train_loss)
        history["train_metrics"].append(train_metric)
        history["valid_metrics"].append(val_metric)

        scheduler.step(val_metric)


        print(f"Epoch {epoch + 1}/{n_epochs}, "
              f"train loss: {history['train_losses'][-1]:.4f}, "
              f"train metric: {history['train_metrics'][-1]:.4f}, "
              f"valid metric: {history['valid_metrics'][-1]:.4f}")

    model.load_state_dict(best_model_state)
    print("Best epoch:", best_epoch)
    print("Best validation accuracy:", best_valid)

    return history

## Comparing different models

### Simple RNN model

In [ ]:
class SimpleRnnModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

input_size = number of features is 15

output_size = number of classes is 24

In [ ]:
torch.manual_seed(42)

simple_model = SimpleRnnModel(input_size=15, hidden_size=32, output_size=24).to(device)

In [ ]:
torch.manual_seed(42)

optimizer = torch.optim.NAdam(simple_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(simple_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 3.1841, train metric: 0.0515, valid metric: 0.0631
Epoch 2/50, train loss: 3.1056, train metric: 0.0674, valid metric: 0.0729
Epoch 3/50, train loss: 3.0011, train metric: 0.0783, valid metric: 0.0849
Epoch 4/50, train loss: 2.9319, train metric: 0.0871, valid metric: 0.0908
Epoch 5/50, train loss: 2.9084, train metric: 0.0915, valid metric: 0.0914
Epoch 6/50, train loss: 2.8959, train metric: 0.0929, valid metric: 0.0938
Epoch 7/50, train loss: 2.8891, train metric: 0.0947, valid metric: 0.0930
Epoch 8/50, train loss: 2.8839, train metric: 0.0949, valid metric: 0.0975
Epoch 9/50, train loss: 2.8796, train metric: 0.0961, valid metric: 0.0961
Epoch 10/50, train loss: 2.8757, train metric: 0.0978, valid metric: 0.0966
Epoch 11/50, train loss: 2.8723, train metric: 0.0980, valid metric: 0.0987
Epoch 12/50, train loss: 2.8683, train metric: 0.0990, valid metric: 0.0999
Epoch 13/50, train loss: 2.8632, train metric: 0.1001, valid metric: 0.1001
Epoch 14/50, train loss: 2.8579, train metric: 0.1024, valid metric: 0.1025
Epoch 15/50, train loss: 2.8512, train metric: 0.1024, valid metric: 0.1051
Epoch 16/50, train loss: 2.8407, train metric: 0.1050, valid metric: 0.1078
Epoch 17/50, train loss: 2.8261, train metric: 0.1062, valid metric: 0.1043
Epoch 18/50, train loss: 2.8313, train metric: 0.1046, valid metric: 0.1061
Epoch 19/50, train loss: 2.8177, train metric: 0.1076, valid metric: 0.1098
Epoch 20/50, train loss: 2.8189, train metric: 0.1077, valid metric: 0.1099
Epoch 21/50, train loss: 2.8118, train metric: 0.1075, valid metric: 0.1116
Epoch 22/50, train loss: 2.8241, train metric: 0.1063, valid metric: 0.1042
Epoch 23/50, train loss: 2.8158, train metric: 0.1080, valid metric: 0.1098
Epoch 24/50, train loss: 2.8117, train metric: 0.1083, valid metric: 0.1029
Epoch 25/50, train loss: 2.8094, train metric: 0.1085, valid metric: 0.1093
Epoch 26/50, train loss: 2.8354, train metric: 0.1060, valid metric: 0.1088
Epoch 27/50, train loss: 2.8360, train metric: 0.1052, valid metric: 0.1053
Epoch 28/50, train loss: 2.8428, train metric: 0.1055, valid metric: 0.1069
Epoch 29/50, train loss: 2.8510, train metric: 0.1033, valid metric: 0.1076
Epoch 30/50, train loss: 2.8401, train metric: 0.1039, valid metric: 0.1049
Epoch 31/50, train loss: 2.8131, train metric: 0.1082, valid metric: 0.1123
Epoch 32/50, train loss: 2.8439, train metric: 0.1042, valid metric: 0.1022
Epoch 33/50, train loss: 2.8296, train metric: 0.1094, valid metric: 0.1078
Epoch 34/50, train loss: 2.8617, train metric: 0.1029, valid metric: 0.1069
Epoch 35/50, train loss: 2.8606, train metric: 0.1044, valid metric: 0.0989
Epoch 36/50, train loss: 2.8491, train metric: 0.1068, valid metric: 0.1078
Epoch 37/50, train loss: 2.8069, train metric: 0.1077, valid metric: 0.1107
Epoch 38/50, train loss: 2.8174, train metric: 0.1076, valid metric: 0.1112
Epoch 39/50, train loss: 2.8337, train metric: 0.1069, valid metric: 0.1143
Epoch 40/50, train loss: 2.7655, train metric: 0.1148, valid metric: 0.1164
Epoch 41/50, train loss: 2.8038, train metric: 0.1111, valid metric: 0.1162
Epoch 42/50, train loss: 2.8410, train metric: 0.1067, valid metric: 0.1010
Epoch 43/50, train loss: 2.8270, train metric: 0.1102, valid metric: 0.1167
Epoch 44/50, train loss: 2.7740, train metric: 0.1159, valid metric: 0.1051
Epoch 45/50, train loss: 2.8157, train metric: 0.1108, valid metric: 0.1086
Epoch 46/50, train loss: 2.7985, train metric: 0.1139, valid metric: 0.0988
Epoch 47/50, train loss: 2.8099, train metric: 0.1133, valid metric: 0.1145
Epoch 48/50, train loss: 2.7938, train metric: 0.1140, valid metric: 0.1170
Epoch 49/50, train loss: 2.7623, train metric: 0.1177, valid metric: 0.1257
Epoch 50/50, train loss: 2.7361, train metric: 0.1207, valid metric: 0.1225

Look at some predictions

In [ ]:
for idx in range(10):
    X, y = valid_dataset[idx]
    X = X.to(device)
    y = y.to(device)

    with torch.no_grad():
        logits = simple_model(X.unsqueeze(0)) # add batch dimension: (100,15) -> (1,100,15)
        pred = logits.argmax(dim=1).item()

    print(f"idx={idx}, predicted={pred}, actual={y.item()}")

idx=0, predicted=15, actual=2
idx=1, predicted=18, actual=18
idx=2, predicted=3, actual=8
idx=3, predicted=21, actual=1
idx=4, predicted=21, actual=6
idx=5, predicted=5, actual=18
idx=6, predicted=3, actual=4
idx=7, predicted=5, actual=7
idx=8, predicted=13, actual=13
idx=9, predicted=23, actual=1

### GRU MODEL

In [ ]:
class GRUModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.GRU(input_size, hidden_size, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

gru_model = GRUModel(input_size=15, hidden_size=32, output_size=24).to(device)

In [ ]:
torch.manual_seed(42)

optimizer = torch.optim.NAdam(gru_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

gru_history = train(gru_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 3.0683, train metric: 0.0698, valid metric: 0.0836
Epoch 2/50, train loss: 2.9310, train metric: 0.0889, valid metric: 0.0973
Epoch 3/50, train loss: 2.8508, train metric: 0.1025, valid metric: 0.1126
Epoch 4/50, train loss: 2.7615, train metric: 0.1200, valid metric: 0.1230
Epoch 5/50, train loss: 2.6931, train metric: 0.1296, valid metric: 0.1311
Epoch 6/50, train loss: 2.6494, train metric: 0.1363, valid metric: 0.1410
Epoch 7/50, train loss: 2.6174, train metric: 0.1433, valid metric: 0.1466
Epoch 8/50, train loss: 2.5890, train metric: 0.1495, valid metric: 0.1499
Epoch 9/50, train loss: 2.5642, train metric: 0.1549, valid metric: 0.1578
Epoch 10/50, train loss: 2.5421, train metric: 0.1590, valid metric: 0.1639
Epoch 11/50, train loss: 2.5212, train metric: 0.1653, valid metric: 0.1660
Epoch 12/50, train loss: 2.5022, train metric: 0.1696, valid metric: 0.1709
Epoch 13/50, train loss: 2.4842, train metric: 0.1759, valid metric: 0.1774
Epoch 14/50, train loss: 2.4650, train metric: 0.1814, valid metric: 0.1864
Epoch 15/50, train loss: 2.4441, train metric: 0.1872, valid metric: 0.1899
Epoch 16/50, train loss: 2.4275, train metric: 0.1939, valid metric: 0.1934
Epoch 17/50, train loss: 2.4130, train metric: 0.1973, valid metric: 0.1984
Epoch 18/50, train loss: 2.4000, train metric: 0.2009, valid metric: 0.2043
Epoch 19/50, train loss: 2.3877, train metric: 0.2051, valid metric: 0.2076
Epoch 20/50, train loss: 2.3754, train metric: 0.2105, valid metric: 0.2054
Epoch 21/50, train loss: 2.3629, train metric: 0.2134, valid metric: 0.2150
Epoch 22/50, train loss: 2.3496, train metric: 0.2178, valid metric: 0.2165
Epoch 23/50, train loss: 2.3375, train metric: 0.2228, valid metric: 0.2193
Epoch 24/50, train loss: 2.3243, train metric: 0.2265, valid metric: 0.2277
Epoch 25/50, train loss: 2.3119, train metric: 0.2323, valid metric: 0.2334
Epoch 26/50, train loss: 2.2985, train metric: 0.2372, valid metric: 0.2313
Epoch 27/50, train loss: 2.2839, train metric: 0.2404, valid metric: 0.2446
Epoch 28/50, train loss: 2.2709, train metric: 0.2449, valid metric: 0.2523
Epoch 29/50, train loss: 2.2581, train metric: 0.2495, valid metric: 0.2483
Epoch 30/50, train loss: 2.2437, train metric: 0.2560, valid metric: 0.2587
Epoch 31/50, train loss: 2.2270, train metric: 0.2616, valid metric: 0.2664
Epoch 32/50, train loss: 2.2144, train metric: 0.2652, valid metric: 0.2633
Epoch 33/50, train loss: 2.2019, train metric: 0.2705, valid metric: 0.2752
Epoch 34/50, train loss: 2.1899, train metric: 0.2739, valid metric: 0.2746
Epoch 35/50, train loss: 2.1792, train metric: 0.2771, valid metric: 0.2794
Epoch 36/50, train loss: 2.1703, train metric: 0.2793, valid metric: 0.2796
Epoch 37/50, train loss: 2.1612, train metric: 0.2818, valid metric: 0.2807
Epoch 38/50, train loss: 2.1570, train metric: 0.2822, valid metric: 0.2864
Epoch 39/50, train loss: 2.1455, train metric: 0.2868, valid metric: 0.2825
Epoch 40/50, train loss: 2.1377, train metric: 0.2898, valid metric: 0.2859
Epoch 41/50, train loss: 2.1321, train metric: 0.2898, valid metric: 0.2942
Epoch 42/50, train loss: 2.1242, train metric: 0.2926, valid metric: 0.2951
Epoch 43/50, train loss: 2.1181, train metric: 0.2954, valid metric: 0.2969
Epoch 44/50, train loss: 2.1135, train metric: 0.2975, valid metric: 0.2942
Epoch 45/50, train loss: 2.1070, train metric: 0.2996, valid metric: 0.2990
Epoch 46/50, train loss: 2.1012, train metric: 0.3006, valid metric: 0.2961
Epoch 47/50, train loss: 2.0978, train metric: 0.3024, valid metric: 0.2980
Epoch 48/50, train loss: 2.0926, train metric: 0.3043, valid metric: 0.2983
Epoch 49/50, train loss: 2.0877, train metric: 0.3036, valid metric: 0.3072
Epoch 50/50, train loss: 2.0818, train metric: 0.3069, valid metric: 0.3065

In [ ]:
for idx in range(10):
    X, y = valid_dataset[idx]
    X = X.to(device)
    y = y.to(device)

    with torch.no_grad():
        gru_logits = gru_model(X.unsqueeze(0)) # add batch dimension: (100,15) -> (1,100,15)
        rnn_logits = simple_model(X.unsqueeze(0))
        gru_pred = gru_logits.argmax(dim=1).item()
        rnn_pred = rnn_logits.argmax(dim=1).item()

    print(f"idx={idx}, gru predicted={gru_pred}, rnn predicted={rnn_pred} actual={y.item()}")

idx=0, gru predicted=2, rnn predicted=15 actual=2
idx=1, gru predicted=10, rnn predicted=18 actual=18
idx=2, gru predicted=8, rnn predicted=3 actual=8
idx=3, gru predicted=1, rnn predicted=21 actual=1
idx=4, gru predicted=19, rnn predicted=21 actual=6
idx=5, gru predicted=4, rnn predicted=5 actual=18
idx=6, gru predicted=15, rnn predicted=3 actual=4
idx=7, gru predicted=2, rnn predicted=5 actual=7
idx=8, gru predicted=13, rnn predicted=13 actual=13
idx=9, gru predicted=23, rnn predicted=23 actual=1

### LSTM Model

In [ ]:
class LSTMModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.LSTM(input_size, hidden_size, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

lstm_model = LSTMModel(input_size=15, hidden_size=32, output_size=24).to(device)

In [ ]:
torch.manual_seed(42)

optimizer = torch.optim.NAdam(lstm_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

lstm_history = train(lstm_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 3.1331, train metric: 0.0585, valid metric: 0.0751
Epoch 2/50, train loss: 2.9703, train metric: 0.0834, valid metric: 0.0909
Epoch 3/50, train loss: 2.8728, train metric: 0.0986, valid metric: 0.1065
Epoch 4/50, train loss: 2.8163, train metric: 0.1075, valid metric: 0.1102
Epoch 5/50, train loss: 2.8597, train metric: 0.1016, valid metric: 0.1123
Epoch 6/50, train loss: 2.7734, train metric: 0.1128, valid metric: 0.1191
Epoch 7/50, train loss: 2.7494, train metric: 0.1167, valid metric: 0.1212
Epoch 8/50, train loss: 2.7268, train metric: 0.1213, valid metric: 0.1176
Epoch 9/50, train loss: 2.7026, train metric: 0.1260, valid metric: 0.1244
Epoch 10/50, train loss: 2.6832, train metric: 0.1279, valid metric: 0.1268
Epoch 11/50, train loss: 2.6666, train metric: 0.1309, valid metric: 0.1293
Epoch 12/50, train loss: 2.6529, train metric: 0.1328, valid metric: 0.1288
Epoch 13/50, train loss: 2.6360, train metric: 0.1372, valid metric: 0.1333
Epoch 14/50, train loss: 2.6206, train metric: 0.1387, valid metric: 0.1383
Epoch 15/50, train loss: 2.6096, train metric: 0.1413, valid metric: 0.1394
Epoch 16/50, train loss: 2.5981, train metric: 0.1440, valid metric: 0.1430
Epoch 17/50, train loss: 2.5860, train metric: 0.1478, valid metric: 0.1455
Epoch 18/50, train loss: 2.5756, train metric: 0.1504, valid metric: 0.1460
Epoch 19/50, train loss: 2.5650, train metric: 0.1519, valid metric: 0.1480
Epoch 20/50, train loss: 2.5584, train metric: 0.1540, valid metric: 0.1532
Epoch 21/50, train loss: 2.5502, train metric: 0.1567, valid metric: 0.1539
Epoch 22/50, train loss: 2.5405, train metric: 0.1583, valid metric: 0.1556
Epoch 23/50, train loss: 2.5306, train metric: 0.1593, valid metric: 0.1593
Epoch 24/50, train loss: 2.5220, train metric: 0.1634, valid metric: 0.1602
Epoch 25/50, train loss: 2.5151, train metric: 0.1633, valid metric: 0.1599
Epoch 26/50, train loss: 2.5057, train metric: 0.1658, valid metric: 0.1654
Epoch 27/50, train loss: 2.4959, train metric: 0.1686, valid metric: 0.1681
Epoch 28/50, train loss: 2.4875, train metric: 0.1700, valid metric: 0.1710
Epoch 29/50, train loss: 2.4785, train metric: 0.1728, valid metric: 0.1727
Epoch 30/50, train loss: 2.4717, train metric: 0.1743, valid metric: 0.1725
Epoch 31/50, train loss: 2.4621, train metric: 0.1785, valid metric: 0.1725
Epoch 32/50, train loss: 2.4552, train metric: 0.1821, valid metric: 0.1808
Epoch 33/50, train loss: 2.4423, train metric: 0.1844, valid metric: 0.1810
Epoch 34/50, train loss: 2.4333, train metric: 0.1884, valid metric: 0.1860
Epoch 35/50, train loss: 2.4229, train metric: 0.1914, valid metric: 0.1911
Epoch 36/50, train loss: 2.4135, train metric: 0.1947, valid metric: 0.1928
Epoch 37/50, train loss: 2.4046, train metric: 0.1974, valid metric: 0.1998
Epoch 38/50, train loss: 2.3950, train metric: 0.2010, valid metric: 0.2017
Epoch 39/50, train loss: 2.3854, train metric: 0.2054, valid metric: 0.2021
Epoch 40/50, train loss: 2.3824, train metric: 0.2080, valid metric: 0.2014
Epoch 41/50, train loss: 2.3655, train metric: 0.2119, valid metric: 0.2127
Epoch 42/50, train loss: 2.3561, train metric: 0.2160, valid metric: 0.2137
Epoch 43/50, train loss: 2.3424, train metric: 0.2202, valid metric: 0.2179
Epoch 44/50, train loss: 2.3328, train metric: 0.2236, valid metric: 0.2258
Epoch 45/50, train loss: 2.3205, train metric: 0.2286, valid metric: 0.2208
Epoch 46/50, train loss: 2.3118, train metric: 0.2298, valid metric: 0.2277
Epoch 47/50, train loss: 2.3028, train metric: 0.2340, valid metric: 0.2293
Epoch 48/50, train loss: 2.2916, train metric: 0.2354, valid metric: 0.2283
Epoch 49/50, train loss: 2.2896, train metric: 0.2365, valid metric: 0.2329
Epoch 50/50, train loss: 2.2789, train metric: 0.2395, valid metric: 0.2399

### CNN - simplified WaveNet
*WaveNet*: stacking 1D convolutional layers, doubling the dilation rate (how spread apart each neuron's inputs are) at every layer. The first conv layer sees two time steps at a time, the nex one sees four time steps, etc.

The lower layers learn short-term patterns, while the higher layers learn long-term patterns.

Custom CausalConv1d module that acts just like an nn.Conv1d module, except the inuts get padded on the left side by the appropriate amount to ensure the sequence preserves the same length.

- kernel_size will be 2 for each layer
- dilation will increase: 1,2,4,8 and then again 1,2,4,8

In [ ]:
import torch.nn.functional as F

class CausalConv1d(nn.Conv1d):
  def forward(self, X):
    padding = (self.kernel_size[0] - 1) * self.dilation[0] # calculate the size of the left-padding we need
    X = F.pad(X, (padding, 0))  # X is the tensor to pad, (padding, 0) is how much to pad to the left and right in the time dimension
    return super().forward(X)

WaveNet model.

Must swap the two dimensions of the nn.Conv1d layer's inputs and outputs: nn.Conv1d expects inputs of shape [*batch size, input features, sequence length*] and produces outputs of shape [*batch size, output features, sequence length*]

while we have inputs [*batch size, sequence length, input features*] (with sequence length 100, input features 15).

We don't need the prediction for all 100 time steps, so we then take the last time step: Z[:, :, -1].

In [ ]:
class WavenetModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    layers = []
    for dilation in (1,2,4,8) * 2: # (1,2,4,8,1,2,4,8)
      conv = CausalConv1d(input_size, hidden_size, kernel_size=2, dilation=dilation)
      layers += [conv, nn.ReLU()]
      input_size = hidden_size
    self.convs = nn.Sequential(*layers)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    Z = X.permute(0,2,1)
    Z = self.convs(Z)
    Z = Z[:, :, -1]
    return self.output(Z)

In [ ]:
torch.manual_seed(42)
wavenet_model = WavenetModel(input_size=15, hidden_size=32, output_size=24).to(device)

optimizer = torch.optim.NAdam(wavenet_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

wavenet_history = train(wavenet_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.9142, train metric: 0.0848, valid metric: 0.1032
Epoch 2/50, train loss: 2.7814, train metric: 0.1061, valid metric: 0.1126
Epoch 3/50, train loss: 2.7440, train metric: 0.1164, valid metric: 0.1087
Epoch 4/50, train loss: 2.7223, train metric: 0.1219, valid metric: 0.1248
Epoch 5/50, train loss: 2.7039, train metric: 0.1277, valid metric: 0.1318
Epoch 6/50, train loss: 2.6913, train metric: 0.1303, valid metric: 0.1288
Epoch 7/50, train loss: 2.6810, train metric: 0.1330, valid metric: 0.1341
Epoch 8/50, train loss: 2.6719, train metric: 0.1353, valid metric: 0.1375
Epoch 9/50, train loss: 2.6642, train metric: 0.1371, valid metric: 0.1387
Epoch 10/50, train loss: 2.6568, train metric: 0.1403, valid metric: 0.1314
Epoch 11/50, train loss: 2.6495, train metric: 0.1417, valid metric: 0.1409
Epoch 12/50, train loss: 2.6431, train metric: 0.1436, valid metric: 0.1442
Epoch 13/50, train loss: 2.6340, train metric: 0.1471, valid metric: 0.1421
Epoch 14/50, train loss: 2.6268, train metric: 0.1484, valid metric: 0.1490
Epoch 15/50, train loss: 2.6181, train metric: 0.1524, valid metric: 0.1484
Epoch 16/50, train loss: 2.6098, train metric: 0.1549, valid metric: 0.1517
Epoch 17/50, train loss: 2.6016, train metric: 0.1593, valid metric: 0.1594
Epoch 18/50, train loss: 2.5922, train metric: 0.1625, valid metric: 0.1583
Epoch 19/50, train loss: 2.5848, train metric: 0.1657, valid metric: 0.1595
Epoch 20/50, train loss: 2.5774, train metric: 0.1678, valid metric: 0.1643
Epoch 21/50, train loss: 2.5704, train metric: 0.1703, valid metric: 0.1656
Epoch 22/50, train loss: 2.5633, train metric: 0.1729, valid metric: 0.1710
Epoch 23/50, train loss: 2.5557, train metric: 0.1744, valid metric: 0.1716
Epoch 24/50, train loss: 2.5483, train metric: 0.1772, valid metric: 0.1679
Epoch 25/50, train loss: 2.5414, train metric: 0.1791, valid metric: 0.1678
Epoch 26/50, train loss: 2.5358, train metric: 0.1817, valid metric: 0.1750
Epoch 27/50, train loss: 2.5288, train metric: 0.1834, valid metric: 0.1738
Epoch 28/50, train loss: 2.5232, train metric: 0.1852, valid metric: 0.1797
Epoch 29/50, train loss: 2.5183, train metric: 0.1866, valid metric: 0.1764
Epoch 30/50, train loss: 2.5118, train metric: 0.1878, valid metric: 0.1821
Epoch 31/50, train loss: 2.5075, train metric: 0.1905, valid metric: 0.1811
Epoch 32/50, train loss: 2.5017, train metric: 0.1924, valid metric: 0.1872
Epoch 33/50, train loss: 2.4979, train metric: 0.1936, valid metric: 0.1868
Epoch 34/50, train loss: 2.4922, train metric: 0.1958, valid metric: 0.1864
Epoch 35/50, train loss: 2.4872, train metric: 0.1974, valid metric: 0.1896
Epoch 36/50, train loss: 2.4836, train metric: 0.1978, valid metric: 0.1892
Epoch 37/50, train loss: 2.4778, train metric: 0.2002, valid metric: 0.1871
Epoch 38/50, train loss: 2.4737, train metric: 0.2000, valid metric: 0.1921
Epoch 39/50, train loss: 2.4681, train metric: 0.2016, valid metric: 0.1933
Epoch 40/50, train loss: 2.4645, train metric: 0.2043, valid metric: 0.1961
Epoch 41/50, train loss: 2.4588, train metric: 0.2047, valid metric: 0.1934
Epoch 42/50, train loss: 2.4554, train metric: 0.2052, valid metric: 0.1929
Epoch 43/50, train loss: 2.4492, train metric: 0.2080, valid metric: 0.2013
Epoch 44/50, train loss: 2.4459, train metric: 0.2084, valid metric: 0.1969
Epoch 45/50, train loss: 2.4415, train metric: 0.2106, valid metric: 0.1963
Epoch 46/50, train loss: 2.4362, train metric: 0.2120, valid metric: 0.2001
Epoch 47/50, train loss: 2.4321, train metric: 0.2131, valid metric: 0.1995
Epoch 48/50, train loss: 2.4282, train metric: 0.2132, valid metric: 0.2023
Epoch 49/50, train loss: 2.4223, train metric: 0.2152, valid metric: 0.2023
Epoch 50/50, train loss: 2.4178, train metric: 0.2179, valid metric: 0.1975

## Comparing hidden sizes in GRU Model

Gru Model with hidden size = 64

In [ ]:
torch.manual_seed(42)

gru_model_64 = GRUModel(input_size=15, hidden_size=64, output_size=24).to(device)

optimizer = torch.optim.NAdam(gru_model_64.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

gru_64_history = train(gru_model_64, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 3.0117, train metric: 0.0807, valid metric: 0.1050
Epoch 2/50, train loss: 2.7969, train metric: 0.1153, valid metric: 0.1287
Epoch 3/50, train loss: 2.6821, train metric: 0.1352, valid metric: 0.1394
Epoch 4/50, train loss: 2.6198, train metric: 0.1474, valid metric: 0.1522
Epoch 5/50, train loss: 2.5692, train metric: 0.1583, valid metric: 0.1586
Epoch 6/50, train loss: 2.5222, train metric: 0.1698, valid metric: 0.1699
Epoch 7/50, train loss: 2.4754, train metric: 0.1812, valid metric: 0.1860
Epoch 8/50, train loss: 2.4354, train metric: 0.1936, valid metric: 0.1950
Epoch 9/50, train loss: 2.3985, train metric: 0.2021, valid metric: 0.1990
Epoch 10/50, train loss: 2.3649, train metric: 0.2135, valid metric: 0.2133
Epoch 11/50, train loss: 2.3332, train metric: 0.2212, valid metric: 0.2263
Epoch 12/50, train loss: 2.3029, train metric: 0.2336, valid metric: 0.2262
Epoch 13/50, train loss: 2.2760, train metric: 0.2411, valid metric: 0.2450
Epoch 14/50, train loss: 2.2476, train metric: 0.2503, valid metric: 0.2543
Epoch 15/50, train loss: 2.2162, train metric: 0.2619, valid metric: 0.2632
Epoch 16/50, train loss: 2.1878, train metric: 0.2719, valid metric: 0.2646
Epoch 17/50, train loss: 2.1625, train metric: 0.2793, valid metric: 0.2758
Epoch 18/50, train loss: 2.1390, train metric: 0.2844, valid metric: 0.2800
Epoch 19/50, train loss: 2.1176, train metric: 0.2909, valid metric: 0.2847
Epoch 20/50, train loss: 2.0990, train metric: 0.2969, valid metric: 0.2887
Epoch 21/50, train loss: 2.0799, train metric: 0.3019, valid metric: 0.3021
Epoch 22/50, train loss: 2.0630, train metric: 0.3087, valid metric: 0.3022
Epoch 23/50, train loss: 2.0469, train metric: 0.3140, valid metric: 0.3070
Epoch 24/50, train loss: 2.0329, train metric: 0.3191, valid metric: 0.3021
Epoch 25/50, train loss: 2.0199, train metric: 0.3220, valid metric: 0.3159
Epoch 26/50, train loss: 2.0087, train metric: 0.3262, valid metric: 0.3213
Epoch 27/50, train loss: 1.9942, train metric: 0.3307, valid metric: 0.3303
Epoch 28/50, train loss: 1.9842, train metric: 0.3348, valid metric: 0.3224
Epoch 29/50, train loss: 1.9724, train metric: 0.3378, valid metric: 0.3385
Epoch 30/50, train loss: 1.9638, train metric: 0.3417, valid metric: 0.3372
Epoch 31/50, train loss: 1.9535, train metric: 0.3448, valid metric: 0.3458
Epoch 32/50, train loss: 1.9435, train metric: 0.3470, valid metric: 0.3470
Epoch 33/50, train loss: 1.9334, train metric: 0.3524, valid metric: 0.3407
Epoch 34/50, train loss: 1.9249, train metric: 0.3558, valid metric: 0.3536
Epoch 35/50, train loss: 1.9168, train metric: 0.3582, valid metric: 0.3551
Epoch 36/50, train loss: 1.9089, train metric: 0.3593, valid metric: 0.3382
Epoch 37/50, train loss: 1.8994, train metric: 0.3646, valid metric: 0.3547
Epoch 38/50, train loss: 1.8915, train metric: 0.3675, valid metric: 0.3643
Epoch 39/50, train loss: 1.8829, train metric: 0.3696, valid metric: 0.3647
Epoch 40/50, train loss: 1.8757, train metric: 0.3720, valid metric: 0.3691
Epoch 41/50, train loss: 1.8665, train metric: 0.3757, valid metric: 0.3695
Epoch 42/50, train loss: 1.8576, train metric: 0.3798, valid metric: 0.3745
Epoch 43/50, train loss: 1.8515, train metric: 0.3811, valid metric: 0.3795
Epoch 44/50, train loss: 1.8425, train metric: 0.3852, valid metric: 0.3798
Epoch 45/50, train loss: 1.8356, train metric: 0.3877, valid metric: 0.3782
Epoch 46/50, train loss: 1.8274, train metric: 0.3886, valid metric: 0.3807
Epoch 47/50, train loss: 1.8206, train metric: 0.3911, valid metric: 0.3872
Epoch 48/50, train loss: 1.8138, train metric: 0.3944, valid metric: 0.3911
Epoch 49/50, train loss: 1.8054, train metric: 0.3973, valid metric: 0.3899
Epoch 50/50, train loss: 1.7981, train metric: 0.3990, valid metric: 0.3980

Gru model with hidden size 128

In [ ]:
torch.manual_seed(42)

gru_model_128 = GRUModel(input_size=15, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(gru_model_128.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

gru_128_history = train(gru_model_128, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.9319, train metric: 0.0948, valid metric: 0.1212
Epoch 2/50, train loss: 2.6910, train metric: 0.1376, valid metric: 0.1503
Epoch 3/50, train loss: 2.5801, train metric: 0.1617, valid metric: 0.1625
Epoch 4/50, train loss: 2.5119, train metric: 0.1798, valid metric: 0.1840
Epoch 5/50, train loss: 2.4495, train metric: 0.1967, valid metric: 0.1990
Epoch 6/50, train loss: 2.3915, train metric: 0.2133, valid metric: 0.2131
Epoch 7/50, train loss: 2.3347, train metric: 0.2302, valid metric: 0.2362
Epoch 8/50, train loss: 2.2794, train metric: 0.2499, valid metric: 0.2586
Epoch 9/50, train loss: 2.2235, train metric: 0.2676, valid metric: 0.2685
Epoch 10/50, train loss: 2.1689, train metric: 0.2842, valid metric: 0.2921
Epoch 11/50, train loss: 2.1205, train metric: 0.2995, valid metric: 0.2984
Epoch 12/50, train loss: 2.0797, train metric: 0.3108, valid metric: 0.3157
Epoch 13/50, train loss: 2.0435, train metric: 0.3213, valid metric: 0.3237
Epoch 14/50, train loss: 2.0091, train metric: 0.3327, valid metric: 0.3326
Epoch 15/50, train loss: 1.9792, train metric: 0.3399, valid metric: 0.3299
Epoch 16/50, train loss: 1.9505, train metric: 0.3501, valid metric: 0.3359
Epoch 17/50, train loss: 1.9253, train metric: 0.3585, valid metric: 0.3496
Epoch 18/50, train loss: 1.9002, train metric: 0.3666, valid metric: 0.3661
Epoch 19/50, train loss: 1.8767, train metric: 0.3732, valid metric: 0.3707
Epoch 20/50, train loss: 1.8553, train metric: 0.3806, valid metric: 0.3724
Epoch 21/50, train loss: 1.8339, train metric: 0.3870, valid metric: 0.3812
Epoch 22/50, train loss: 1.8151, train metric: 0.3931, valid metric: 0.3866
Epoch 23/50, train loss: 1.7980, train metric: 0.3989, valid metric: 0.3894
Epoch 24/50, train loss: 1.7804, train metric: 0.4033, valid metric: 0.3982
Epoch 25/50, train loss: 1.7639, train metric: 0.4085, valid metric: 0.3940
Epoch 26/50, train loss: 1.7504, train metric: 0.4147, valid metric: 0.4118
Epoch 27/50, train loss: 1.7368, train metric: 0.4189, valid metric: 0.4078
Epoch 28/50, train loss: 1.7234, train metric: 0.4215, valid metric: 0.4154
Epoch 29/50, train loss: 1.7108, train metric: 0.4264, valid metric: 0.4187
Epoch 30/50, train loss: 1.6982, train metric: 0.4316, valid metric: 0.4080
Epoch 31/50, train loss: 1.6870, train metric: 0.4327, valid metric: 0.4219
Epoch 32/50, train loss: 1.6772, train metric: 0.4369, valid metric: 0.4297
Epoch 33/50, train loss: 1.6660, train metric: 0.4393, valid metric: 0.4301
Epoch 34/50, train loss: 1.6566, train metric: 0.4436, valid metric: 0.4360
Epoch 35/50, train loss: 1.6465, train metric: 0.4467, valid metric: 0.4322
Epoch 36/50, train loss: 1.6376, train metric: 0.4488, valid metric: 0.4381
Epoch 37/50, train loss: 1.6282, train metric: 0.4526, valid metric: 0.4440
Epoch 38/50, train loss: 1.6185, train metric: 0.4558, valid metric: 0.4442
Epoch 39/50, train loss: 1.6101, train metric: 0.4577, valid metric: 0.4504
Epoch 40/50, train loss: 1.6003, train metric: 0.4614, valid metric: 0.4522
Epoch 41/50, train loss: 1.5909, train metric: 0.4660, valid metric: 0.4509
Epoch 42/50, train loss: 1.5821, train metric: 0.4690, valid metric: 0.4505
Epoch 43/50, train loss: 1.5726, train metric: 0.4721, valid metric: 0.4563
Epoch 44/50, train loss: 1.5626, train metric: 0.4747, valid metric: 0.4638
Epoch 45/50, train loss: 1.5556, train metric: 0.4781, valid metric: 0.4608
Epoch 46/50, train loss: 1.5465, train metric: 0.4801, valid metric: 0.4551
Epoch 47/50, train loss: 1.5373, train metric: 0.4833, valid metric: 0.4601
Epoch 48/50, train loss: 1.5292, train metric: 0.4864, valid metric: 0.4760
Epoch 49/50, train loss: 1.5198, train metric: 0.4907, valid metric: 0.4772
Epoch 50/50, train loss: 1.5121, train metric: 0.4923, valid metric: 0.4682

#### Save the model weights

In [ ]:
torch.save(
    gru_model_128.state_dict(),
    "/content/drive/MyDrive/Challengedata/gru_128_model.pt"
)

#### Upload the model weights

In [ ]:
gru_model_128 = GRUModel(
    input_size=15,
    hidden_size=128,
    output_size=24
)

gru_model_128.load_state_dict(
    torch.load("/content/drive/MyDrive/Challengedata/gru_128_model.pt", map_location=device)
)

gru_model_128.to(device)
gru_model_128.eval()

## Create submission

We first need to prepreocess the test data.

We predict the test set using `gru_model_128` and create the submission file.

In [ ]:
test = pd.read_parquet("/content/drive/MyDrive/Challengedata/Xtest.parquet")

In [ ]:
test = test[['obs_id','price', 'bid', 'ask', 'bid_size', 'ask_size', 'flux', 'action', 'venue']]
test['venue'] = test['venue'].apply(str)
test = pd.get_dummies(test, dtype=float)
test = test.set_index('obs_id')

In [ ]:
X_test = torch.tensor(test.values, dtype=torch.float32)
X_test = X_test.reshape(-1, 100, 15)

In [ ]:
del test
gc.collect()

266

Create a test_loader because we want to predict in batches rather than send all the data to the GPU at once.

In [ ]:
test_dataset = TensorDataset(X_test)
test_loader = DataLoader(test_dataset, batch_size=256)

Predict the data

In [ ]:
gru_model_128.eval()

predictions = []

with torch.no_grad():
    for (X_batch,) in test_loader:
        X_batch = X_batch.to(device)

        logits = gru_model_128(X_batch)
        y_pred = logits.argmax(dim=1)

        predictions.extend(y_pred.cpu().numpy())

Save the predictions to csv

In [ ]:
submission = pd.DataFrame({
    "obs_id": range(len(predictions)),
    "eqt_code_cat": predictions
})

submission.to_csv(
    "/content/drive/MyDrive/Challengedata/submission.csv",
    index=False
)

## Deep GRU Model

In [29]:
class DeepGRUModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.GRU(input_size, hidden_size, num_layers=2, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

In [30]:
torch.manual_seed(42)

deep_gru_model_128 = DeepGRUModel(input_size=20, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(deep_gru_model_128.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(deep_gru_model_128, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.7282, train metric: 0.1251, valid metric: 0.1545
Epoch 2/50, train loss: 2.5432, train metric: 0.1694, valid metric: 0.1809
Epoch 3/50, train loss: 2.4503, train metric: 0.1951, valid metric: 0.1991
Epoch 4/50, train loss: 2.3820, train metric: 0.2115, valid metric: 0.2189
Epoch 5/50, train loss: 2.3161, train metric: 0.2323, valid metric: 0.2440
Epoch 6/50, train loss: 2.2294, train metric: 0.2605, valid metric: 0.2656
Epoch 7/50, train loss: 2.1502, train metric: 0.2816, valid metric: 0.2865
Epoch 8/50, train loss: 2.0827, train metric: 0.3021, valid metric: 0.2975
Epoch 9/50, train loss: 2.0187, train metric: 0.3207, valid metric: 0.3181
Epoch 10/50, train loss: 1.9554, train metric: 0.3428, valid metric: 0.3466
Epoch 11/50, train loss: 1.8979, train metric: 0.3620, valid metric: 0.3584
Epoch 12/50, train loss: 1.8422, train metric: 0.3809, valid metric: 0.3771
Epoch 13/50, train loss: 1.7906, train metric: 0.3989, valid metric: 0.4001
Epoch 14/50, train loss: 1.7388, train metric: 0.4156, valid metric: 0.4137
Epoch 15/50, train loss: 1.6922, train metric: 0.4324, valid metric: 0.4252
Epoch 16/50, train loss: 1.6485, train metric: 0.4448, valid metric: 0.4389
Epoch 17/50, train loss: 1.6111, train metric: 0.4566, valid metric: 0.4556
Epoch 18/50, train loss: 1.5755, train metric: 0.4691, valid metric: 0.4560
Epoch 19/50, train loss: 1.5419, train metric: 0.4800, valid metric: 0.4402
Epoch 20/50, train loss: 1.5103, train metric: 0.4916, valid metric: 0.4752
Epoch 21/50, train loss: 1.4804, train metric: 0.4996, valid metric: 0.4847
Epoch 22/50, train loss: 1.4476, train metric: 0.5122, valid metric: 0.5002
Epoch 23/50, train loss: 1.4224, train metric: 0.5200, valid metric: 0.5104
Epoch 24/50, train loss: 1.3957, train metric: 0.5291, valid metric: 0.5081
Epoch 25/50, train loss: 1.3719, train metric: 0.5363, valid metric: 0.5202
Epoch 26/50, train loss: 1.3485, train metric: 0.5443, valid metric: 0.5210
Epoch 27/50, train loss: 1.3266, train metric: 0.5518, valid metric: 0.5344
Epoch 28/50, train loss: 1.3059, train metric: 0.5583, valid metric: 0.5356
Epoch 29/50, train loss: 1.2869, train metric: 0.5644, valid metric: 0.5270
Epoch 30/50, train loss: 1.2684, train metric: 0.5700, valid metric: 0.5482
Epoch 31/50, train loss: 1.2512, train metric: 0.5764, valid metric: 0.5455
Epoch 32/50, train loss: 1.2334, train metric: 0.5819, valid metric: 0.5536
Epoch 33/50, train loss: 1.2192, train metric: 0.5867, valid metric: 0.5586
Epoch 34/50, train loss: 1.2033, train metric: 0.5920, valid metric: 0.5648
Epoch 35/50, train loss: 1.1894, train metric: 0.5962, valid metric: 0.5677
Epoch 36/50, train loss: 1.1742, train metric: 0.6000, valid metric: 0.5724
Epoch 37/50, train loss: 1.1607, train metric: 0.6061, valid metric: 0.5754
Epoch 38/50, train loss: 1.1467, train metric: 0.6101, valid metric: 0.5672
Epoch 39/50, train loss: 1.1346, train metric: 0.6147, valid metric: 0.5802
Epoch 40/50, train loss: 1.1218, train metric: 0.6178, valid metric: 0.5836
Epoch 41/50, train loss: 1.1105, train metric: 0.6222, valid metric: 0.5830
Epoch 42/50, train loss: 1.0997, train metric: 0.6258, valid metric: 0.5779
Epoch 43/50, train loss: 1.0884, train metric: 0.6297, valid metric: 0.5864
Epoch 44/50, train loss: 1.0755, train metric: 0.6331, valid metric: 0.5913
Epoch 45/50, train loss: 1.0644, train metric: 0.6375, valid metric: 0.5902
Epoch 46/50, train loss: 1.0550, train metric: 0.6391, valid metric: 0.5926
Epoch 47/50, train loss: 1.0446, train metric: 0.6436, valid metric: 0.5966
Epoch 48/50, train loss: 1.0344, train metric: 0.6474, valid metric: 0.5970
Epoch 49/50, train loss: 1.0240, train metric: 0.6492, valid metric: 0.5984
Epoch 50/50, train loss: 1.0164, train metric: 0.6521, valid metric: 0.6035
Best epoch: 50
Best validation accuracy: 0.6034514904022217

In [31]:
history_2 = train(deep_gru_model_128, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=10)

Epoch 1/10, train loss: 1.0060, train metric: 0.6559, valid metric: 0.5896
Epoch 2/10, train loss: 0.9963, train metric: 0.6588, valid metric: 0.6036
Epoch 3/10, train loss: 0.9874, train metric: 0.6608, valid metric: 0.6084
Epoch 4/10, train loss: 0.9812, train metric: 0.6635, valid metric: 0.6039
Epoch 5/10, train loss: 0.9696, train metric: 0.6663, valid metric: 0.6000
Epoch 6/10, train loss: 0.9614, train metric: 0.6697, valid metric: 0.6113
Epoch 7/10, train loss: 0.9535, train metric: 0.6722, valid metric: 0.6105
Epoch 8/10, train loss: 0.9441, train metric: 0.6746, valid metric: 0.6053
Epoch 9/10, train loss: 0.9372, train metric: 0.6770, valid metric: 0.6135
Epoch 10/10, train loss: 0.9285, train metric: 0.6808, valid metric: 0.6097
Best epoch: 9
Best validation accuracy: 0.6135261058807373

### Save & load model

Save the model: this is trained **without normalization of the inputs** and with 2 gru layers.

In [32]:
torch.save(
    deep_gru_model_128.state_dict(),
    "/content/drive/MyDrive/Challengedata/deep_gru_model_128.pt"
)

Load the model

In [ ]:
deep_gru_model_128.load_state_dict(
    torch.load("/content/drive/MyDrive/Challengedata/deep_gru_model_128.pt")
)