<a href="https://colab.research.google.com/github/lricci03/challengedata/blob/main/CFM2024-new/joint_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Joint model: RNN and engineered features

In [1]:
import torch
import torch.nn as nn

if torch.cuda.is_available():
  device = 'cuda'
elif torch.backends.mps.is_available():
  device = 'mps'
else:
  device = 'cpu'

In [2]:
import pandas as pd

In [3]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

## Sequential Features and Target

In [36]:
df = pd.read_parquet("/content/drive/MyDrive/Challengedata/Xtrain.parquet")

In [37]:
df_num = df[['obs_id','price', 'bid', 'ask', 'bid_size', 'ask_size', 'flux', 'action', 'venue']]
df_num['venue'] = df_num['venue'].apply(str)
df_num = pd.get_dummies(df_num, dtype=float)

/tmp/ipykernel_1301/4138682116.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_num['venue'] = df_num['venue'].apply(str)

In [ ]:
df_num.head()

,obs_id,price,bid,ask,bid_size,ask_size,flux,action_A,action_D,action_U,venue_0,venue_1,venue_2,venue_3,venue_4,venue_5
0,0,0.30,0.0,0.01,100,1,100,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0,-0.17,0.0,0.01,100,1,100,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0,0.28,0.0,0.01,100,1,-100,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0,0.30,0.0,0.01,100,1,100,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0,0.37,0.0,0.01,100,1,-100,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

Don't need df anymore

In [38]:
import gc

del df
gc.collect()

773

In [7]:
targets = pd.read_csv("/content/drive/MyDrive/Challengedata/y_train_or6m3Ta.csv")

Ensure alignment

In [8]:
targets = targets.set_index("obs_id")
df_num = df_num.set_index("obs_id")

In [ ]:
targets.head()

        eqt_code_cat
obs_id
0                 10
1                 15
2                  0
3                 13
4                  0

The first 6 feature positions of df_num are numerical: [0,1,2,3,4,5]

In [ ]:
df_num.iloc[:,0:6]

        price   bid   ask  bid_size  ask_size  flux
obs_id
0        0.30  0.00  0.01       100         1   100
0       -0.17  0.00  0.01       100         1   100
0        0.28  0.00  0.01       100         1  -100
0        0.30  0.00  0.01       100         1   100
0        0.37  0.00  0.01       100         1  -100
...       ...   ...   ...       ...       ...   ...
160799   1.32  0.01  0.06       735       261  -100
160799   0.06  0.01  0.06       735       361   100
160799   1.26  0.01  0.06       735       361   100
160799   1.26  0.01  0.06       735       361   100
160799   0.00  0.01  0.06       635       361     1

[16080000 rows x 6 columns]

Reshape X. This reinterprets every consecutive block of 100 rows as one sample. The -1 means: infer this dimension automatically.

In [39]:
import torch
import torch.nn as nn

X_seq = torch.tensor(df_num.values, dtype=torch.float32)
X_seq = X_seq.reshape(-1, 100, 15)
y = torch.tensor(targets.values.squeeze(), dtype=torch.long)

NameError: name 'targets' is not defined

Delete the dataframes

In [ ]:
del df_num, targets
gc.collect()

## Engineered Features

In [11]:
df_eng = pd.read_csv("/content/drive/MyDrive/Challengedata/eng_features.csv")

In [ ]:
df_eng.head()

,obs_id,median_price,median_mid_price,mean_spread,median_spread,std_spread,min_spread,max_spread,mean_bid_size,median_bid_size,...,std_flux,add_ratio,delete_ratio,update_ratio,venue_4_ratio,venue_1_ratio,venue_5_ratio,venue_2_ratio,venue_0_ratio,venue_3_ratio
0,0,0.00,0.010,0.0152,0.02,0.005021,0.01,0.02,190.60,100.0,...,93.739861,0.51,0.49,0.00,0.59,0.14,0.07,0.13,0.05,0.02
1,1,0.01,0.040,0.0392,0.04,0.006917,0.02,0.06,290.94,300.0,...,94.011927,0.49,0.43,0.08,0.51,0.07,0.21,0.10,0.06,0.05
2,2,0.01,0.005,0.0107,0.01,0.002564,0.01,0.02,1902.15,1510.0,...,151.864373,0.54,0.46,0.00,0.44,0.02,0.19,0.01,0.11,0.23
3,3,0.21,0.150,0.1310,0.10,0.046482,0.10,0.20,275.13,200.0,...,74.986447,0.50,0.49,0.01,0.43,0.18,0.09,0.11,0.18,0.01
4,4,0.02,0.020,0.0174,0.02,0.004408,0.01,0.02,143.15,122.5,...,126.849955,0.48,0.52,0.00,0.42,0.09,0.18,0.02,0.19,0.10

In [12]:
df_eng = df_eng.set_index("obs_id")

In [13]:
X_eng = torch.tensor(df_eng.values, dtype=torch.float32)

In [14]:
X_seq.shape, X_eng.shape, y.shape

(torch.Size([160800, 100, 15]), torch.Size([160800, 30]), torch.Size([160800]))

## Train and Validation set

In [40]:
X_seq_train = X_seq[:128640]
X_seq_valid = X_seq[128640:]

X_eng_train = X_eng[:128640]
X_eng_valid = X_eng[128640:]

y_train = y[:128640]
y_valid = y[128640:]

### Scaling engineered features

We scale the engineered features.

In [16]:
torch.isnan(X_eng).sum()

tensor(0)

Compute mean and standard deviation of the test set, then apply the scaling to both train and validation.

In [17]:
mean = X_eng_train.mean(dim=0, keepdim=True)
std = X_eng_train.std(dim=0, keepdim=True)

# avoid division by zero for constant features
std[std == 0] = 1.0

X_eng_train = (X_eng_train - mean) / std
X_eng_valid = (X_eng_valid - mean) / std

### Scaling sequential features

We scale **some of the** sequential features, only the numerical ones (not one-hot-encoded categorical ones).

The indices of the numerical features are [0,1,2,3,4,5]. [0,1,2] are price, bid, ask.
We scale **only bid_size, ask_size, flux**: [3,4,5]

In [29]:
num_idx = [3, 4, 5]

In [30]:
mean = X_seq_train[:, :, num_idx].mean(dim=(0, 1), keepdim=True)
std = X_seq_train[:, :, num_idx].std(dim=(0, 1), keepdim=True)

std[std == 0] = 1.0

In [31]:
X_seq_train[:, :, num_idx] = (X_seq_train[:, :, num_idx] - mean) / std

X_seq_valid[:, :, num_idx] = (X_seq_valid[:, :, num_idx] - mean) / std

## Dataset and DataLoader

In [18]:
from torch.utils.data import Dataset
import torch

class StockDataset(Dataset):
    def __init__(self, X_seq, X_eng, y):
        self.X_seq = X_seq
        self.X_eng = X_eng
        self.y = y

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return (
            self.X_seq[idx],
            self.X_eng[idx],
            self.y[idx]
        )

In [41]:
train_dataset = StockDataset(X_seq_train, X_eng_train, y_train)
valid_dataset = StockDataset(X_seq_valid, X_eng_valid, y_valid)

In [42]:
from torch.utils.data import DataLoader

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True
)
valid_loader = DataLoader(valid_dataset, batch_size=64)

## Joint GRU model

In [24]:
import torch
import torch.nn as nn

class JointGRUModel(nn.Module):
    def __init__(self, n_seq_features, n_engineered_features, hidden_size=128, n_classes=24):
        super().__init__()

        self.gru = nn.GRU(
            input_size=n_seq_features,
            hidden_size=hidden_size,
            batch_first=True
        )

        self.classifier = nn.Linear(
            hidden_size + n_engineered_features,
            n_classes
        )

    def forward(self, x_seq, x_eng):

        # x_seq: (batch_size, 100, n_seq_features)

        outputs, last_state = self.gru(x_seq)

        # For a 1-layer GRU:
        # outputs shape: [batch_size, window length (100), hidden_size)
        # outputs[:, -1] shape: [batch_size, hidden_size]
        h_gru = outputs[:, -1]

        # x_eng:
        # (batch_size, n_engineered_features)

        x = torch.cat([h_gru, x_eng], dim=1)

        # x:
        # (batch_size, 128 + n_engineered_features)

        logits = self.classifier(x)

        return logits

## Train and evaluation functions

We need to modify slightly since the batches are now of the form: x_seq, x_eng, y instead of previously: x y

In [21]:
%pip install -q torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 25.1 MB/s eta 0:00:00

In [23]:
import torchmetrics
import copy

def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_seq, X_eng, y in data_loader:
            X_seq, X_eng, y = X_seq.to(device), X_eng.to(device), y.to(device)

            logits = model(X_seq, X_eng)

            y_class = logits.argmax(dim=1)
            metric.update(y_class, y)
    return metric.compute()

def train(model, optimizer, loss_fn, metric, train_loader, valid_loader,
          n_epochs, patience=20, factor=0.1):

    best_valid = -float("inf")
    best_model_state = None
    best_epoch = None

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max", # we monitor accuracy
        patience=patience,
        factor=factor)
    history = {"train_losses": [], "train_metrics": [], "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.0
        metric.reset()
        model.train()
        for X_seq, X_eng, y in train_loader:
            X_seq, X_eng, y = X_seq.to(device), X_eng.to(device), y.to(device)

            logits = model(X_seq, X_eng)

            loss = loss_fn(logits, y)

            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

            y_class = logits.argmax(dim=1)
            metric.update(y_class, y)

        train_loss = total_loss / len(train_loader)
        train_metric = metric.compute().item()
        val_metric = evaluate_tm(model, valid_loader, metric).item()

        if val_metric > best_valid:
          best_valid = val_metric
          best_model_state = copy.deepcopy(model.state_dict())
          best_epoch = epoch +1 # +1 bc epoch starts at 0

        history["train_losses"].append(train_loss)
        history["train_metrics"].append(train_metric)
        history["valid_metrics"].append(val_metric)

        scheduler.step(val_metric)

        print(f"Epoch {epoch + 1}/{n_epochs}, "
              f"train loss: {history['train_losses'][-1]:.4f}, "
              f"train metric: {history['train_metrics'][-1]:.4f}, "
              f"valid metric: {history['valid_metrics'][-1]:.4f}")

    model.load_state_dict(best_model_state)
    print("Best epoch:", best_epoch)
    print("Best validation accuracy:", best_valid)

    return history

## Train the model

In [27]:
torch.manual_seed(42)

joint_model = JointGRUModel(n_seq_features=15, n_engineered_features=30, hidden_size=128, n_classes=24).to(device)

check the gpu before training

In [24]:
torch.cuda.is_available()

True

In [29]:
torch.manual_seed(42)

optimizer = torch.optim.NAdam(joint_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(joint_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.6676, train metric: 0.1602, valid metric: 0.2369
Epoch 2/50, train loss: 2.3125, train metric: 0.2558, valid metric: 0.2740
Epoch 3/50, train loss: 2.2220, train metric: 0.2794, valid metric: 0.2863
Epoch 4/50, train loss: 2.1716, train metric: 0.2920, valid metric: 0.2973
Epoch 5/50, train loss: 2.1387, train metric: 0.2993, valid metric: 0.3016
Epoch 6/50, train loss: 2.1147, train metric: 0.3053, valid metric: 0.3093
Epoch 7/50, train loss: 2.0961, train metric: 0.3108, valid metric: 0.3136
Epoch 8/50, train loss: 2.0805, train metric: 0.3146, valid metric: 0.3159
Epoch 9/50, train loss: 2.0658, train metric: 0.3203, valid metric: 0.3157
Epoch 10/50, train loss: 2.0516, train metric: 0.3247, valid metric: 0.3278
Epoch 11/50, train loss: 2.0361, train metric: 0.3293, valid metric: 0.3329
Epoch 12/50, train loss: 2.0192, train metric: 0.3359, valid metric: 0.3345
Epoch 13/50, train loss: 1.9984, train metric: 0.3420, valid metric: 0.3435
Epoch 14/50, train loss: 1.9778, train metric: 0.3477, valid metric: 0.3441
Epoch 15/50, train loss: 1.9608, train metric: 0.3513, valid metric: 0.3512
Epoch 16/50, train loss: 1.9462, train metric: 0.3553, valid metric: 0.3592
Epoch 17/50, train loss: 1.9328, train metric: 0.3595, valid metric: 0.3578
Epoch 18/50, train loss: 1.9214, train metric: 0.3619, valid metric: 0.3611
Epoch 19/50, train loss: 1.9104, train metric: 0.3646, valid metric: 0.3681
Epoch 20/50, train loss: 1.8998, train metric: 0.3692, valid metric: 0.3662
Epoch 21/50, train loss: 1.8891, train metric: 0.3713, valid metric: 0.3692
Epoch 22/50, train loss: 1.8786, train metric: 0.3754, valid metric: 0.3740
Epoch 23/50, train loss: 1.8680, train metric: 0.3776, valid metric: 0.3738
Epoch 24/50, train loss: 1.8580, train metric: 0.3806, valid metric: 0.3809
Epoch 25/50, train loss: 1.8479, train metric: 0.3849, valid metric: 0.3812
Epoch 26/50, train loss: 1.8377, train metric: 0.3871, valid metric: 0.3819
Epoch 27/50, train loss: 1.8278, train metric: 0.3905, valid metric: 0.3859
Epoch 28/50, train loss: 1.8176, train metric: 0.3931, valid metric: 0.3928
Epoch 29/50, train loss: 1.8080, train metric: 0.3963, valid metric: 0.3921
Epoch 30/50, train loss: 1.7983, train metric: 0.3993, valid metric: 0.3954
Epoch 31/50, train loss: 1.7885, train metric: 0.4011, valid metric: 0.4009
Epoch 32/50, train loss: 1.7787, train metric: 0.4046, valid metric: 0.3945
Epoch 33/50, train loss: 1.7675, train metric: 0.4092, valid metric: 0.4051
Epoch 34/50, train loss: 1.7558, train metric: 0.4126, valid metric: 0.4087
Epoch 35/50, train loss: 1.7440, train metric: 0.4154, valid metric: 0.4137
Epoch 36/50, train loss: 1.7331, train metric: 0.4184, valid metric: 0.4169
Epoch 37/50, train loss: 1.7231, train metric: 0.4213, valid metric: 0.4216
Epoch 38/50, train loss: 1.7137, train metric: 0.4243, valid metric: 0.4194
Epoch 39/50, train loss: 1.7045, train metric: 0.4281, valid metric: 0.4234
Epoch 40/50, train loss: 1.6942, train metric: 0.4300, valid metric: 0.4255
Epoch 41/50, train loss: 1.6857, train metric: 0.4332, valid metric: 0.4269
Epoch 42/50, train loss: 1.6771, train metric: 0.4350, valid metric: 0.4320
Epoch 43/50, train loss: 1.6683, train metric: 0.4387, valid metric: 0.4324
Epoch 44/50, train loss: 1.6605, train metric: 0.4404, valid metric: 0.4312
Epoch 45/50, train loss: 1.6531, train metric: 0.4422, valid metric: 0.4372
Epoch 46/50, train loss: 1.6444, train metric: 0.4440, valid metric: 0.4357
Epoch 47/50, train loss: 1.6379, train metric: 0.4473, valid metric: 0.4424
Epoch 48/50, train loss: 1.6302, train metric: 0.4486, valid metric: 0.4429
Epoch 49/50, train loss: 1.6231, train metric: 0.4513, valid metric: 0.4460
Epoch 50/50, train loss: 1.6164, train metric: 0.4536, valid metric: 0.4436

In [30]:
history2 = train(joint_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=20)

Epoch 1/20, train loss: 1.6090, train metric: 0.4550, valid metric: 0.4429
Epoch 2/20, train loss: 1.6022, train metric: 0.4567, valid metric: 0.4486
Epoch 3/20, train loss: 1.5961, train metric: 0.4588, valid metric: 0.4508
Epoch 4/20, train loss: 1.5893, train metric: 0.4603, valid metric: 0.4512
Epoch 5/20, train loss: 1.5837, train metric: 0.4624, valid metric: 0.4540
Epoch 6/20, train loss: 1.5776, train metric: 0.4641, valid metric: 0.4503
Epoch 7/20, train loss: 1.5713, train metric: 0.4667, valid metric: 0.4506
Epoch 8/20, train loss: 1.5657, train metric: 0.4676, valid metric: 0.4564
Epoch 9/20, train loss: 1.5599, train metric: 0.4702, valid metric: 0.4570
Epoch 10/20, train loss: 1.5533, train metric: 0.4705, valid metric: 0.4562
Epoch 11/20, train loss: 1.5483, train metric: 0.4738, valid metric: 0.4613
Epoch 12/20, train loss: 1.5423, train metric: 0.4751, valid metric: 0.4628
Epoch 13/20, train loss: 1.5367, train metric: 0.4758, valid metric: 0.4617
Epoch 14/20, train loss: 1.5317, train metric: 0.4779, valid metric: 0.4611
Epoch 15/20, train loss: 1.5257, train metric: 0.4797, valid metric: 0.4644
Epoch 16/20, train loss: 1.5201, train metric: 0.4818, valid metric: 0.4659
Epoch 17/20, train loss: 1.5147, train metric: 0.4831, valid metric: 0.4674
Epoch 18/20, train loss: 1.5085, train metric: 0.4857, valid metric: 0.4705
Epoch 19/20, train loss: 1.5030, train metric: 0.4869, valid metric: 0.4701
Epoch 20/20, train loss: 1.4976, train metric: 0.4888, valid metric: 0.4740

## Engineered Only Model

In [ ]:
class EngOnlyModel(nn.Module):
    def __init__(self, n_engineered_features, n_classes=24):
        super().__init__()
        self.classifier = nn.Linear(n_engineered_features, n_classes)

    def forward(self, x_eng):
        return self.classifier(x_eng)

In [ ]:
import torchmetrics

def evaluate_tm2(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)

            y_class = y_pred.argmax(dim=1)
            metric.update(y_class, y_batch)
    return metric.compute()

def train2(model, optimizer, loss_fn, metric, train_loader, valid_loader,
          n_epochs, patience=20, factor=0.1):

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max", # we monitor accuracy
        patience=patience,
        factor=factor)
    history = {"train_losses": [], "train_metrics": [], "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.0
        metric.reset()
        model.train()
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            loss = loss_fn(y_pred, y_batch)

            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

            y_class = y_pred.detach().argmax(dim=1)
            metric.update(y_class, y_batch)

        train_loss = total_loss / len(train_loader)
        train_metric = metric.compute().item()
        val_metric = evaluate_tm2(model, valid_loader, metric).item()

        history["train_losses"].append(train_loss)
        history["train_metrics"].append(train_metric)
        history["valid_metrics"].append(val_metric)

        scheduler.step(val_metric)

        print(f"Epoch {epoch + 1}/{n_epochs}, "
              f"train loss: {history['train_losses'][-1]:.4f}, "
              f"train metric: {history['train_metrics'][-1]:.4f}, "
              f"valid metric: {history['valid_metrics'][-1]:.4f}")
    return history

In [ ]:
print(X_eng_train.shape, y_train.shape)
print(X_eng_valid.shape, y_valid.shape)

torch.Size([128640, 30]) torch.Size([128640])
torch.Size([32160, 30]) torch.Size([32160])

In [ ]:
from torch.utils.data import TensorDataset

train_eng_only_dataset = TensorDataset(X_eng_train, y_train)
valid_eng_only_dataset = TensorDataset(X_eng_valid, y_valid)

In [ ]:
from torch.utils.data import DataLoader

train_eng_only_loader = DataLoader(train_eng_only_dataset, batch_size=64, shuffle=True)
valid_eng_only_loader = DataLoader(valid_eng_only_dataset, batch_size=32)

In [ ]:
torch.manual_seed(42)

eng_only_model = EngOnlyModel(n_engineered_features=30, n_classes=24).to(device)

In [ ]:
torch.manual_seed(42)

optimizer = torch.optim.NAdam(eng_only_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train2(eng_only_model, optimizer, criterion, accuracy, train_eng_only_loader,
                valid_eng_only_loader, n_epochs=50)

Epoch 1/50, train loss: 3.0480, train metric: 0.1025, valid metric: 0.1532
Epoch 2/50, train loss: 2.7929, train metric: 0.1765, valid metric: 0.1935
Epoch 3/50, train loss: 2.6746, train metric: 0.2034, valid metric: 0.2080
Epoch 4/50, train loss: 2.6076, train metric: 0.2144, valid metric: 0.2178
Epoch 5/50, train loss: 2.5654, train metric: 0.2220, valid metric: 0.2238
Epoch 6/50, train loss: 2.5363, train metric: 0.2276, valid metric: 0.2277
Epoch 7/50, train loss: 2.5147, train metric: 0.2312, valid metric: 0.2318
Epoch 8/50, train loss: 2.4980, train metric: 0.2343, valid metric: 0.2350
Epoch 9/50, train loss: 2.4845, train metric: 0.2368, valid metric: 0.2373
Epoch 10/50, train loss: 2.4735, train metric: 0.2393, valid metric: 0.2393
Epoch 11/50, train loss: 2.4641, train metric: 0.2416, valid metric: 0.2407
Epoch 12/50, train loss: 2.4562, train metric: 0.2426, valid metric: 0.2428
Epoch 13/50, train loss: 2.4492, train metric: 0.2442, valid metric: 0.2439
Epoch 14/50, train loss: 2.4432, train metric: 0.2455, valid metric: 0.2456
Epoch 15/50, train loss: 2.4377, train metric: 0.2462, valid metric: 0.2472
Epoch 16/50, train loss: 2.4329, train metric: 0.2473, valid metric: 0.2488
Epoch 17/50, train loss: 2.4286, train metric: 0.2481, valid metric: 0.2501
Epoch 18/50, train loss: 2.4247, train metric: 0.2490, valid metric: 0.2512
Epoch 19/50, train loss: 2.4211, train metric: 0.2496, valid metric: 0.2522
Epoch 20/50, train loss: 2.4178, train metric: 0.2503, valid metric: 0.2525
Epoch 21/50, train loss: 2.4147, train metric: 0.2511, valid metric: 0.2532
Epoch 22/50, train loss: 2.4120, train metric: 0.2517, valid metric: 0.2539
Epoch 23/50, train loss: 2.4093, train metric: 0.2519, valid metric: 0.2548
Epoch 24/50, train loss: 2.4069, train metric: 0.2522, valid metric: 0.2557
Epoch 25/50, train loss: 2.4047, train metric: 0.2534, valid metric: 0.2566
Epoch 26/50, train loss: 2.4025, train metric: 0.2538, valid metric: 0.2564
Epoch 27/50, train loss: 2.4006, train metric: 0.2540, valid metric: 0.2565
Epoch 28/50, train loss: 2.3987, train metric: 0.2544, valid metric: 0.2570
Epoch 29/50, train loss: 2.3969, train metric: 0.2547, valid metric: 0.2572
Epoch 30/50, train loss: 2.3952, train metric: 0.2554, valid metric: 0.2579
Epoch 31/50, train loss: 2.3936, train metric: 0.2557, valid metric: 0.2584
Epoch 32/50, train loss: 2.3921, train metric: 0.2561, valid metric: 0.2584
Epoch 33/50, train loss: 2.3906, train metric: 0.2561, valid metric: 0.2590
Epoch 34/50, train loss: 2.3892, train metric: 0.2565, valid metric: 0.2593
Epoch 35/50, train loss: 2.3879, train metric: 0.2569, valid metric: 0.2592
Epoch 36/50, train loss: 2.3867, train metric: 0.2574, valid metric: 0.2595
Epoch 37/50, train loss: 2.3854, train metric: 0.2573, valid metric: 0.2600
Epoch 38/50, train loss: 2.3843, train metric: 0.2576, valid metric: 0.2604
Epoch 39/50, train loss: 2.3832, train metric: 0.2575, valid metric: 0.2601
Epoch 40/50, train loss: 2.3821, train metric: 0.2583, valid metric: 0.2603
Epoch 41/50, train loss: 2.3811, train metric: 0.2584, valid metric: 0.2602
Epoch 42/50, train loss: 2.3801, train metric: 0.2579, valid metric: 0.2608
Epoch 43/50, train loss: 2.3792, train metric: 0.2587, valid metric: 0.2611
Epoch 44/50, train loss: 2.3782, train metric: 0.2591, valid metric: 0.2613
Epoch 45/50, train loss: 2.3774, train metric: 0.2589, valid metric: 0.2621
Epoch 46/50, train loss: 2.3765, train metric: 0.2593, valid metric: 0.2618
Epoch 47/50, train loss: 2.3757, train metric: 0.2595, valid metric: 0.2621
Epoch 48/50, train loss: 2.3749, train metric: 0.2598, valid metric: 0.2617
Epoch 49/50, train loss: 2.3741, train metric: 0.2601, valid metric: 0.2623
Epoch 50/50, train loss: 2.3733, train metric: 0.2601, valid metric: 0.2629

## Joint 2-GRU model

In [25]:
import torch
import torch.nn as nn

class Joint2GRUModel(nn.Module):
    def __init__(self, n_seq_features, n_engineered_features, hidden_size=128, n_classes=24):
        super().__init__()

        self.gru = nn.GRU(input_size=n_seq_features, hidden_size=hidden_size, num_layers=2, batch_first=True)

        self.classifier = nn.Linear(
            hidden_size + n_engineered_features,
            n_classes
        )

    def forward(self, x_seq, x_eng):

        # x_seq: (batch_size, 100, n_seq_features)

        outputs, last_state = self.gru(x_seq)

        # For a 1-layer GRU:
        # outputs shape: [batch_size, window length (100), hidden_size)
        # outputs[:, -1] shape: [batch_size, hidden_size]
        h_gru = outputs[:, -1]

        # x_eng:
        # (batch_size, n_engineered_features)

        x = torch.cat([h_gru, x_eng], dim=1)

        # x:
        # (batch_size, 128 + n_engineered_features)

        logits = self.classifier(x)

        return logits

In [26]:
torch.manual_seed(42)

joint_model_2 = Joint2GRUModel(n_seq_features=15, n_engineered_features=30, hidden_size=128, n_classes=24).to(device)

torch.manual_seed(42)

optimizer = torch.optim.NAdam(joint_model_2.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(joint_model_2, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.6972, train metric: 0.1527, valid metric: 0.2194
Epoch 2/50, train loss: 2.4308, train metric: 0.2341, valid metric: 0.2497
Epoch 3/50, train loss: 2.3355, train metric: 0.2562, valid metric: 0.2641
Epoch 4/50, train loss: 2.2744, train metric: 0.2701, valid metric: 0.2796
Epoch 5/50, train loss: 2.2225, train metric: 0.2837, valid metric: 0.2875
Epoch 6/50, train loss: 2.1788, train metric: 0.2950, valid metric: 0.2964
Epoch 7/50, train loss: 2.1439, train metric: 0.3056, valid metric: 0.2989
Epoch 8/50, train loss: 2.1142, train metric: 0.3118, valid metric: 0.3105
Epoch 9/50, train loss: 2.0869, train metric: 0.3204, valid metric: 0.3175
Epoch 10/50, train loss: 2.0619, train metric: 0.3276, valid metric: 0.3268
Epoch 11/50, train loss: 2.0333, train metric: 0.3375, valid metric: 0.3285
Epoch 12/50, train loss: 2.0037, train metric: 0.3481, valid metric: 0.3332
Epoch 13/50, train loss: 1.9739, train metric: 0.3562, valid metric: 0.3532
Epoch 14/50, train loss: 1.9420, train metric: 0.3659, valid metric: 0.3590
Epoch 15/50, train loss: 1.9102, train metric: 0.3757, valid metric: 0.3668
Epoch 16/50, train loss: 1.8790, train metric: 0.3847, valid metric: 0.3782
Epoch 17/50, train loss: 1.8485, train metric: 0.3932, valid metric: 0.3853
Epoch 18/50, train loss: 1.8217, train metric: 0.4007, valid metric: 0.3939
Epoch 19/50, train loss: 1.7967, train metric: 0.4075, valid metric: 0.3973
Epoch 20/50, train loss: 1.7728, train metric: 0.4134, valid metric: 0.3917
Epoch 21/50, train loss: 1.7510, train metric: 0.4197, valid metric: 0.4089
Epoch 22/50, train loss: 1.7313, train metric: 0.4250, valid metric: 0.4163
Epoch 23/50, train loss: 1.7116, train metric: 0.4315, valid metric: 0.4236
Epoch 24/50, train loss: 1.6929, train metric: 0.4388, valid metric: 0.4162
Epoch 25/50, train loss: 1.6758, train metric: 0.4420, valid metric: 0.4254
Epoch 26/50, train loss: 1.6598, train metric: 0.4470, valid metric: 0.4265
Epoch 27/50, train loss: 1.6449, train metric: 0.4518, valid metric: 0.4371
Epoch 28/50, train loss: 1.6316, train metric: 0.4552, valid metric: 0.4339
Epoch 29/50, train loss: 1.6150, train metric: 0.4603, valid metric: 0.4383
Epoch 30/50, train loss: 1.6013, train metric: 0.4644, valid metric: 0.4501
Epoch 31/50, train loss: 1.5877, train metric: 0.4688, valid metric: 0.4540
Epoch 32/50, train loss: 1.5748, train metric: 0.4731, valid metric: 0.4531
Epoch 33/50, train loss: 1.5605, train metric: 0.4783, valid metric: 0.4604
Epoch 34/50, train loss: 1.5472, train metric: 0.4823, valid metric: 0.4589
Epoch 35/50, train loss: 1.5340, train metric: 0.4864, valid metric: 0.4664
Epoch 36/50, train loss: 1.5198, train metric: 0.4920, valid metric: 0.4701
Epoch 37/50, train loss: 1.5064, train metric: 0.4958, valid metric: 0.4692
Epoch 38/50, train loss: 1.4948, train metric: 0.4998, valid metric: 0.4771
Epoch 39/50, train loss: 1.4808, train metric: 0.5035, valid metric: 0.4813
Epoch 40/50, train loss: 1.4693, train metric: 0.5073, valid metric: 0.4886
Epoch 41/50, train loss: 1.4567, train metric: 0.5111, valid metric: 0.4806
Epoch 42/50, train loss: 1.4450, train metric: 0.5140, valid metric: 0.4910
Epoch 43/50, train loss: 1.4337, train metric: 0.5192, valid metric: 0.4913
Epoch 44/50, train loss: 1.4206, train metric: 0.5228, valid metric: 0.4917
Epoch 45/50, train loss: 1.4102, train metric: 0.5259, valid metric: 0.5008
Epoch 46/50, train loss: 1.3959, train metric: 0.5302, valid metric: 0.5038
Epoch 47/50, train loss: 1.3858, train metric: 0.5340, valid metric: 0.5017
Epoch 48/50, train loss: 1.3741, train metric: 0.5381, valid metric: 0.5106
Epoch 49/50, train loss: 1.3640, train metric: 0.5408, valid metric: 0.5078
Epoch 50/50, train loss: 1.3542, train metric: 0.5428, valid metric: 0.5043
Best epoch: 48
Best validation accuracy: 0.5106032490730286

In [27]:
history_2 = train(joint_model_2, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 1.3633, train metric: 0.5424, valid metric: 0.5125
Epoch 2/50, train loss: 1.3530, train metric: 0.5441, valid metric: 0.5065
Epoch 3/50, train loss: 1.3426, train metric: 0.5476, valid metric: 0.5110
Epoch 4/50, train loss: 1.3316, train metric: 0.5511, valid metric: 0.5229
Epoch 5/50, train loss: 1.3206, train metric: 0.5542, valid metric: 0.5199
Epoch 6/50, train loss: 1.3101, train metric: 0.5579, valid metric: 0.5274
Epoch 7/50, train loss: 1.3008, train metric: 0.5604, valid metric: 0.5273
Epoch 8/50, train loss: 1.2900, train metric: 0.5636, valid metric: 0.5294
Epoch 9/50, train loss: 1.2813, train metric: 0.5666, valid metric: 0.5288
Epoch 10/50, train loss: 1.2707, train metric: 0.5692, valid metric: 0.5275
Epoch 11/50, train loss: 1.2621, train metric: 0.5738, valid metric: 0.5305
Epoch 12/50, train loss: 1.2528, train metric: 0.5761, valid metric: 0.5362
Epoch 13/50, train loss: 1.2445, train metric: 0.5805, valid metric: 0.5308
Epoch 14/50, train loss: 1.2347, train metric: 0.5832, valid metric: 0.5371
Epoch 15/50, train loss: 1.2262, train metric: 0.5837, valid metric: 0.5299
Epoch 16/50, train loss: 1.2179, train metric: 0.5875, valid metric: 0.5425
Epoch 17/50, train loss: 1.2111, train metric: 0.5900, valid metric: 0.5456
Epoch 18/50, train loss: 1.2018, train metric: 0.5930, valid metric: 0.5509
Epoch 19/50, train loss: 1.1960, train metric: 0.5948, valid metric: 0.5455
Epoch 20/50, train loss: 1.1874, train metric: 0.5974, valid metric: 0.5463
Epoch 21/50, train loss: 1.1790, train metric: 0.5997, valid metric: 0.5465
Epoch 22/50, train loss: 1.1740, train metric: 0.6026, valid metric: 0.5454
Epoch 23/50, train loss: 1.1643, train metric: 0.6061, valid metric: 0.5509
Epoch 24/50, train loss: 1.1581, train metric: 0.6071, valid metric: 0.5516
Epoch 25/50, train loss: 1.1502, train metric: 0.6102, valid metric: 0.5466
Epoch 26/50, train loss: 1.1441, train metric: 0.6118, valid metric: 0.5586
Epoch 27/50, train loss: 1.1375, train metric: 0.6147, valid metric: 0.5517
Epoch 28/50, train loss: 1.1311, train metric: 0.6162, valid metric: 0.5613
Epoch 29/50, train loss: 1.1245, train metric: 0.6178, valid metric: 0.5618
Epoch 30/50, train loss: 1.1170, train metric: 0.6199, valid metric: 0.5569
Epoch 31/50, train loss: 1.1106, train metric: 0.6227, valid metric: 0.5552
Epoch 32/50, train loss: 1.1049, train metric: 0.6241, valid metric: 0.5585
Epoch 33/50, train loss: 1.0994, train metric: 0.6263, valid metric: 0.5613
Epoch 34/50, train loss: 1.0924, train metric: 0.6294, valid metric: 0.5568
Epoch 35/50, train loss: 1.0872, train metric: 0.6313, valid metric: 0.5638
Epoch 36/50, train loss: 1.0809, train metric: 0.6326, valid metric: 0.5656
Epoch 37/50, train loss: 1.0740, train metric: 0.6360, valid metric: 0.5645
Epoch 38/50, train loss: 1.0682, train metric: 0.6373, valid metric: 0.5632
Epoch 39/50, train loss: 1.0626, train metric: 0.6397, valid metric: 0.5599
Epoch 40/50, train loss: 1.0581, train metric: 0.6399, valid metric: 0.5727
Epoch 41/50, train loss: 1.0507, train metric: 0.6426, valid metric: 0.5704
Epoch 42/50, train loss: 1.0447, train metric: 0.6442, valid metric: 0.5612
Epoch 43/50, train loss: 1.0392, train metric: 0.6465, valid metric: 0.5693
Epoch 44/50, train loss: 1.0363, train metric: 0.6481, valid metric: 0.5730
Epoch 45/50, train loss: 1.0288, train metric: 0.6489, valid metric: 0.5731
Epoch 46/50, train loss: 1.0237, train metric: 0.6515, valid metric: 0.5721
Epoch 47/50, train loss: 1.0182, train metric: 0.6540, valid metric: 0.5737
Epoch 48/50, train loss: 1.0123, train metric: 0.6565, valid metric: 0.5693
Epoch 49/50, train loss: 1.0089, train metric: 0.6572, valid metric: 0.5771
Epoch 50/50, train loss: 1.0025, train metric: 0.6592, valid metric: 0.5748
Best epoch: 49
Best validation accuracy: 0.5771144032478333

### Save and load the model

In [28]:
torch.save(
    joint_model_2.state_dict(),
    "/content/drive/MyDrive/Challengedata/deep_joint_model.pt"
)

In [ ]:
joint_model_2.load_state_dict(
    torch.load("/content/drive/MyDrive/Challengedata/deep_joint_model.pt")
)

## Joint 2-GRU trained on normalized data

We run the normalization cells for the sequential inputs, and re-run the dataset and dataloader.

In [34]:
torch.manual_seed(42)

joint_model_3 = Joint2GRUModel(n_seq_features=15, n_engineered_features=30, hidden_size=128, n_classes=24).to(device)

torch.manual_seed(42)

optimizer = torch.optim.NAdam(joint_model_3.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(joint_model_3, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 2.5466, train metric: 0.1738, valid metric: 0.2441
Epoch 2/50, train loss: 2.2719, train metric: 0.2637, valid metric: 0.2802
Epoch 3/50, train loss: 2.1873, train metric: 0.2901, valid metric: 0.2968
Epoch 4/50, train loss: 2.1340, train metric: 0.3035, valid metric: 0.3089
Epoch 5/50, train loss: 2.0952, train metric: 0.3131, valid metric: 0.3121
Epoch 6/50, train loss: 2.0577, train metric: 0.3245, valid metric: 0.3265
Epoch 7/50, train loss: 2.0150, train metric: 0.3368, valid metric: 0.3389
Epoch 8/50, train loss: 1.9837, train metric: 0.3438, valid metric: 0.3372
Epoch 9/50, train loss: 1.9605, train metric: 0.3490, valid metric: 0.3447
Epoch 10/50, train loss: 1.9421, train metric: 0.3546, valid metric: 0.3522
Epoch 11/50, train loss: 1.9248, train metric: 0.3596, valid metric: 0.3589
Epoch 12/50, train loss: 1.9081, train metric: 0.3649, valid metric: 0.3618
Epoch 13/50, train loss: 1.8914, train metric: 0.3701, valid metric: 0.3687
Epoch 14/50, train loss: 1.8731, train metric: 0.3762, valid metric: 0.3706
Epoch 15/50, train loss: 1.8554, train metric: 0.3804, valid metric: 0.3778
Epoch 16/50, train loss: 1.8383, train metric: 0.3851, valid metric: 0.3810
Epoch 17/50, train loss: 1.8213, train metric: 0.3894, valid metric: 0.3866
Epoch 18/50, train loss: 1.8074, train metric: 0.3935, valid metric: 0.3900
Epoch 19/50, train loss: 1.7930, train metric: 0.3974, valid metric: 0.3926
Epoch 20/50, train loss: 1.7787, train metric: 0.4018, valid metric: 0.3975
Epoch 21/50, train loss: 1.7657, train metric: 0.4059, valid metric: 0.3998
Epoch 22/50, train loss: 1.7535, train metric: 0.4094, valid metric: 0.4042
Epoch 23/50, train loss: 1.7394, train metric: 0.4135, valid metric: 0.4059
Epoch 24/50, train loss: 1.7264, train metric: 0.4169, valid metric: 0.4110
Epoch 25/50, train loss: 1.7123, train metric: 0.4215, valid metric: 0.4125
Epoch 26/50, train loss: 1.6989, train metric: 0.4265, valid metric: 0.4193
Epoch 27/50, train loss: 1.6856, train metric: 0.4300, valid metric: 0.4233
Epoch 28/50, train loss: 1.6699, train metric: 0.4337, valid metric: 0.4244
Epoch 29/50, train loss: 1.6553, train metric: 0.4372, valid metric: 0.4296
Epoch 30/50, train loss: 1.6409, train metric: 0.4423, valid metric: 0.4314
Epoch 31/50, train loss: 1.6270, train metric: 0.4462, valid metric: 0.4356
Epoch 32/50, train loss: 1.6117, train metric: 0.4501, valid metric: 0.4405
Epoch 33/50, train loss: 1.5979, train metric: 0.4563, valid metric: 0.4406
Epoch 34/50, train loss: 1.5835, train metric: 0.4592, valid metric: 0.4462
Epoch 35/50, train loss: 1.5695, train metric: 0.4648, valid metric: 0.4556
Epoch 36/50, train loss: 1.5560, train metric: 0.4673, valid metric: 0.4545
Epoch 37/50, train loss: 1.5431, train metric: 0.4723, valid metric: 0.4644
Epoch 38/50, train loss: 1.5302, train metric: 0.4749, valid metric: 0.4650
Epoch 39/50, train loss: 1.5169, train metric: 0.4802, valid metric: 0.4698
Epoch 40/50, train loss: 1.5040, train metric: 0.4836, valid metric: 0.4713
Epoch 41/50, train loss: 1.4914, train metric: 0.4874, valid metric: 0.4754
Epoch 42/50, train loss: 1.4787, train metric: 0.4899, valid metric: 0.4732
Epoch 43/50, train loss: 1.4652, train metric: 0.4942, valid metric: 0.4831
Epoch 44/50, train loss: 1.4534, train metric: 0.4981, valid metric: 0.4836
Epoch 45/50, train loss: 1.4418, train metric: 0.5027, valid metric: 0.4894
Epoch 46/50, train loss: 1.4288, train metric: 0.5058, valid metric: 0.4897
Epoch 47/50, train loss: 1.4180, train metric: 0.5093, valid metric: 0.4925
Epoch 48/50, train loss: 1.4059, train metric: 0.5133, valid metric: 0.4976
Epoch 49/50, train loss: 1.3945, train metric: 0.5160, valid metric: 0.4981
Epoch 50/50, train loss: 1.3829, train metric: 0.5217, valid metric: 0.4986
Best epoch: 50
Best validation accuracy: 0.4986318349838257

The validation accuracy is comparable as training on non-normalized sequential data.

The joint model performs worse than the sequential-only model.

## Deep Joint 2-GRU

Construct a deep joint model, where by 'deep' we mean that we add a top linear layer when combining sequential and engineered data.

In [43]:
import torch
import torch.nn as nn

class DeepJoint2GRUModel(nn.Module):
    def __init__(self, n_seq_features, n_engineered_features, hidden_size=128, n_classes=24):
        super().__init__()

        self.gru = nn.GRU(input_size=n_seq_features, hidden_size=hidden_size, num_layers=2, batch_first=True)

        self.classifier = nn.Sequential(
            nn.Linear(hidden_size + n_engineered_features, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, n_classes)
            )

    def forward(self, x_seq, x_eng):

        # x_seq: (batch_size, 100, n_seq_features)

        outputs, last_state = self.gru(x_seq)

        # For a 1-layer GRU:
        # outputs shape: [batch_size, window length (100), hidden_size)
        # outputs[:, -1] shape: [batch_size, hidden_size]
        h_gru = outputs[:, -1]

        # x_eng:
        # (batch_size, n_engineered_features)

        x = torch.cat([h_gru, x_eng], dim=1)

        # x:
        # (batch_size, 128 + n_engineered_features)

        logits = self.classifier(x)

        return logits

Deep Joint 2Gru model trained with non-normalized sequential inputs.

In [45]:
torch.manual_seed(42)

deep_joint_model = DeepJoint2GRUModel(n_seq_features=15, n_engineered_features=30, hidden_size=128, n_classes=24).to(device)

torch.manual_seed(42)

optimizer = torch.optim.NAdam(deep_joint_model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train(deep_joint_model, optimizer, criterion, accuracy, train_loader,
                valid_loader, n_epochs=50)

Epoch 1/50, train loss: 3.0123, train metric: 0.1110, valid metric: 0.1436
Epoch 2/50, train loss: 2.7101, train metric: 0.1440, valid metric: 0.1536
Epoch 3/50, train loss: 2.6501, train metric: 0.1585, valid metric: 0.1701
Epoch 4/50, train loss: 2.6188, train metric: 0.1675, valid metric: 0.1368
Epoch 5/50, train loss: 2.5975, train metric: 0.1736, valid metric: 0.1714
Epoch 6/50, train loss: 2.5699, train metric: 0.1781, valid metric: 0.1782
Epoch 7/50, train loss: 2.5518, train metric: 0.1846, valid metric: 0.1863
Epoch 8/50, train loss: 2.5378, train metric: 0.1882, valid metric: 0.1868
Epoch 9/50, train loss: 2.5269, train metric: 0.1909, valid metric: 0.1933
Epoch 10/50, train loss: 2.5134, train metric: 0.1932, valid metric: 0.1999
Epoch 11/50, train loss: 2.5046, train metric: 0.1969, valid metric: 0.2012
Epoch 12/50, train loss: 2.4954, train metric: 0.2009, valid metric: 0.1951
Epoch 13/50, train loss: 2.4861, train metric: 0.2035, valid metric: 0.2001
Epoch 14/50, train loss: 2.4719, train metric: 0.2064, valid metric: 0.2055
Epoch 15/50, train loss: 2.4641, train metric: 0.2097, valid metric: 0.2062
Epoch 16/50, train loss: 2.4543, train metric: 0.2114, valid metric: 0.2113
Epoch 17/50, train loss: 2.4458, train metric: 0.2150, valid metric: 0.2199
Epoch 18/50, train loss: 2.4364, train metric: 0.2171, valid metric: 0.2195
Epoch 19/50, train loss: 2.4202, train metric: 0.2224, valid metric: 0.2200
Epoch 20/50, train loss: 2.4155, train metric: 0.2248, valid metric: 0.2258
Epoch 21/50, train loss: 2.4027, train metric: 0.2279, valid metric: 0.2257
Epoch 22/50, train loss: 2.3930, train metric: 0.2316, valid metric: 0.2305
Epoch 23/50, train loss: 2.3822, train metric: 0.2343, valid metric: 0.2367
Epoch 24/50, train loss: 2.3741, train metric: 0.2358, valid metric: 0.2323
Epoch 25/50, train loss: 2.3612, train metric: 0.2396, valid metric: 0.2420
Epoch 26/50, train loss: 2.3518, train metric: 0.2429, valid metric: 0.2422
Epoch 27/50, train loss: 2.3439, train metric: 0.2449, valid metric: 0.2476
Epoch 28/50, train loss: 2.3391, train metric: 0.2460, valid metric: 0.2466
Epoch 29/50, train loss: 2.3323, train metric: 0.2482, valid metric: 0.2505
Epoch 30/50, train loss: 2.3245, train metric: 0.2496, valid metric: 0.2419
Epoch 31/50, train loss: 2.3180, train metric: 0.2522, valid metric: 0.2586
Epoch 32/50, train loss: 2.3151, train metric: 0.2529, valid metric: 0.2532
Epoch 33/50, train loss: 2.3075, train metric: 0.2551, valid metric: 0.2543
Epoch 34/50, train loss: 2.3007, train metric: 0.2563, valid metric: 0.2611
Epoch 35/50, train loss: 2.2959, train metric: 0.2589, valid metric: 0.2633
Epoch 36/50, train loss: 2.2916, train metric: 0.2608, valid metric: 0.2572
Epoch 37/50, train loss: 2.2864, train metric: 0.2614, valid metric: 0.2547
Epoch 38/50, train loss: 2.2826, train metric: 0.2614, valid metric: 0.2599
Epoch 39/50, train loss: 2.2791, train metric: 0.2646, valid metric: 0.2683
Epoch 40/50, train loss: 2.2744, train metric: 0.2657, valid metric: 0.2575
Epoch 41/50, train loss: 2.2701, train metric: 0.2676, valid metric: 0.2667
Epoch 42/50, train loss: 2.2654, train metric: 0.2669, valid metric: 0.2629
Epoch 43/50, train loss: 2.2634, train metric: 0.2682, valid metric: 0.2715
Epoch 44/50, train loss: 2.2589, train metric: 0.2701, valid metric: 0.2629
Epoch 45/50, train loss: 2.2567, train metric: 0.2716, valid metric: 0.2751
Epoch 46/50, train loss: 2.2521, train metric: 0.2734, valid metric: 0.2687
Epoch 47/50, train loss: 2.2488, train metric: 0.2746, valid metric: 0.2745
Epoch 48/50, train loss: 2.2441, train metric: 0.2755, valid metric: 0.2714
Epoch 49/50, train loss: 2.2419, train metric: 0.2751, valid metric: 0.2773
Epoch 50/50, train loss: 2.2387, train metric: 0.2774, valid metric: 0.2759
Best epoch: 49
Best validation accuracy: 0.27730098366737366